### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by ChrysanthCow** [MehVahdJukaar/FarmersDelightRefabricated#10]
The official statement for 1.20.4 is that we will be waiting for a bit before we get something out, while the mod is new, we'd prefer to prioritise bugfixes.

**Comment by ChrysanthCow** [comment]
Update: We'll be updating when Porting Lib does.

**Comment by kingstairs** [comment]
Will this be updated to support 1.20.6 as well? Thanks.

**Comment by ChrysanthCow** [comment]
> Will this be updated to support 1.20.6 as well? Thanks.

When Porting Lib updates, absolutely.

**Comment by ikeb200** [comment]
On GitHub porting lib is 1.20.4

**Comment by ChrysanthCow** [comment]
But there's no release, so we can't do much.

**Comment by ChrysanthCow** [comment]
1.21 will be a definite.

**Comment by MehVahdJukaar** [comment]
Small "update" on this. Please dont ask for ports, we are waiting for Porting Lib to release on 1.21

**Comment by Omarforce** [comment]
> Small "update" on this. Please dont ask for ports, we are waiting for Porting Lib to release on 1.21

hey any idea why the portinglib update is taking so long despite it being a 1.21 github version

**Comment by MehVahdJukaar** [comment]
no idea. Not up to us. Having a 1.21 branch just means stuff is being worked on. Could be 1% done or 99% done for what we know
