### ISSUE TITLE
Recipes display is not available with latest version of REI

### ISSUE THREAD

**Issue by MUYUTwilighter** [MehVahdJukaar/FarmersDelightRefabricated#100]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.6

### Fabric Loader version

0.15.11

### Fabric API version

0.92.2+1.20.1

### Description

Recipes whose type is created by Farmer's Delight is not shown in latest version (I tested with 12.1.780 and above) of REI.
But it works fine when I tested with REI 12.1.750.

### Steps to reproduce

Install Farmer's Delight of any version with REI 12.1.780 or above.

### Mod list

- Farmer's Delight 2.1.6
- REI 12.1.780 or above
- Other necessary dependencies

### Logs

https://paste.ee/p/pZHM8

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Fixed in 1.20.1+2.1.7
