### ISSUE TITLE
Exception ticking world caused by....Tomatoes?

### ISSUE THREAD

**Issue by BallisticAri** [MehVahdJukaar/FarmersDelightRefabricated#101]
### Minecraft version

1.21.1

### Farmer's Delight version

2.1.10

### Fabric Loader version

0.16.9

### Fabric API version

0.107.0

### Description

Every time a tomato ripens on the plant, the game crashes. THis does not occur when the mod is alone.

### Steps to reproduce

1. create world
2. find tomato crop in village
3. game crashes

### Mod list

- advancementplaques 1.6.6
	- amendments 1.21-1.2.18
	- appleskin 3.0.6+mc1.21
	- architectury 13.0.8
	- artifacts 12.0.6
	   |-- com_electronwill_night-config_core 3.8.0
	   |-- com_electronwill_night-config_toml 3.8.0
	   \-- expandability 12.0.0
	- athena 4.0.1
	- balm-fabric 21.0.20
	   \-- kuma_api 21.0.5-SNAPSHOT
	- betteradvancements 0.4.3.21
	- betterchunkloading 1.21-4.5
	- betterdeserttemples 1.21.1-Fabric-4.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.21.1-Fabric-5.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterendisland 1.21.1-Fabric-3.1.1
	   \-- org_reflections_reflections 0.10.2
	- betterfortresses 1.21.1-Fabric-3.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterfpsdist 1.21-6.0
	- betterjungletemples 1.21.1-Fabric-3.1.1
	   \-- org_reflections_reflections 0.10.2
	- bettermineshafts 1.21.1-Fabric-5.1.1
	   \-- org_reflections_reflections 0.10.2
	- betteroceanmonuments 1.21.1-Fabric-4.1.1
	   \-- org_reflections_reflections 0.10.2
	- betterpingdisplay 1.1.1
	- betterstrongholds 1.21.1-Fabric-5.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterwitchhuts 1.21.1-Fabric-4.1.1
	   \-- org_reflections_reflections 0.10.2
	- biomesoplenty 21.1.0.7
	- biomeswevegone 2.2.0
	- blastingraw 1.21.1-2-fabric
	- blastingsand 1.21.1-11-fabric
	- bookshelf 21.1.13
	- cardinal-components 6.1.1
	   |-- cardinal-components-base 6.1.1
	   |-- cardinal-components-block 6.1.1
	   |-- cardinal-components-chunk 6.1.1
	   |-- cardinal-components-entity 6.1.1
	   |-- cardinal-components-item 6.1.1
	   |-- cardinal-components-level 6.1.1
	   |-- cardinal-components-scoreboard 6.1.1
	   \-- cardinal-components-world 6.1.1
	- chat_heads 0.13.4
	- chatimpressiveanimation 1.2.0+mc1.21.1
	- chunksending 1.21-2.8
	- chunky 1.4.16
	- clayblasting 1.21.1-0-fabric
	- cloth-config 15.0.140
	   \-- cloth-basic-math 0.6.1
	- clumps 19.0.0.1
	- cobweb 1.1.3
	- collective 7.87
	- comforts 9.0.3+1.21.1
	   \-- spectrelib 0.17.2+1.21
	        |-- com_electronwill_night-config_core 3.8.0
	        \-- com_electronwill_night-config_toml 3.8.0
	- cookingforblockheads 21.1.3
	- corgilib 5.0.0.2
	   |-- com_electronwill_night-config_core 3.8.0
	   \-- com_electronwill_night-config_toml 3.8.0
	- cupboard 1.21-2.7
	- default_skill_trees 1.1
	- diagonalfences 21.1.0
	   \-- diagonalblocks 21.1.0
	- diagonalwalls 21.1.0
	   \-- diagonalblocks 21.1.0
	- diagonalwindows 21.1.0
	   \-- diagonalblocks 21.1.0
	- easyanvils 21.1.0
	- easymagic 21.1.0
	- enchdesc 21.1.5
	- entity_model_features 2.2.6
	- entity_pin_cushions 1.0
	- entity_texture_features 6.2.5
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- fabric-api 0.107.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.69+b559734419
	   |-- fabric-biome-api-v1 13.0.30+be1ed2d719
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.17+b559734419
	   |-- fabric-convention-tags-v1 2.1.1+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.1+7fd4837519
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.2.0+e49211d819
	   |-- fabric-data-generation-api-v1 20.2.22+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.1+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.4.0+0f6c53cd19
	   |-- fabric-loot-api-v2 3.0.15+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.3+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.1+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.1+5b5275af19
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.1+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- farmingforblockheads 21.1.2
	- forgeconfigapiport 21.1.1
	   |-- com_electronwill_night-config_core 3.8.0
	   \-- com_electronwill_night-config_toml 3.8.0
	- ftbbackups2 1.0.28
	- ftbessentials 2101.1.0
	- ftblibrary 2101.1.4
	- ftbultimine 2101.1.1
	- geckolib 4.6.6
	- geophilic 3.1.4
	- glitchcore 2.1.0.0
	   \-- net_jodah_typetools 0.6.3
	- handcrafted 4.0.2
	- highlighter 1.1.11
	- hopobettermineshaft 1.2.8
	- hopobetterruinedportal 1.4.4
	- hopobetterunderwaterruins 1.2.1
	- iceberg 1.2.7
	- inventoryessentials 21.1.1
	- inventoryhud 3.4.26
	- iris 1.8.0-beta.4+mc1.21.1
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- ironchest 2.0.4
	   \-- libgui 11.1.0+1.21
	        |-- jankson 8.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- itemborders 1.2.5
	- jade 15.8.2+fabric
	- jamlib 1.2.2+1.21.1
	   \-- blue_endless_jankson 1.2.3
	- java 21
	- lavender 0.1.13+1.21
	   |-- lavender-md 0.1.2+1.21
	   \-- lavender-md-owo-ui 0.1.2+1.21
	- leavesbegone 21.1.0
	- legendarytooltips 1.4.11
	- lightweight-inventory-sorting 1.1.2+1.21
	- macawsbridgesbop 1.21-1.0
	- macawsroofsbop 1.21-1.0
	- mcwbridges 3.0.0
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- mcwfencesbop 1.21-1.1
	- mcwfurnitures 3.3.0
	- mcwfurnituresbop 1.21.1-1.1
	- mcwlights 1.1.1
	- mcwpaths 1.0.5
	- mcwroofs 2.3.1
	- mcwstairs 1.0.0
	- mcwtrpdoors 1.1.3
	- mcwwindows 2.3.2
	- minecraft 1.21.1
	- modmenu 11.0.3
	- moonlight 1.21-2.15.6
	- mousetweaks 2.26
	- neat 1.21-40-FABRIC
	   \-- fiber 0.23.0-2
	- netherrackblasting 1.21.1-0-fabric
	- notenoughanimations 1.7.6
	- ohthetreesyoullgrow 5.0.3
	- openpartiesandclaims 0.23.2
	- oritech 0.10.3
	   \-- team_reborn_energy 4.1.0
	- owo 0.12.15+1.21
	   |-- io_wispforest_endec 0.1.5
	   |-- io_wispforest_endec_gson 0.1.3
	   |-- io_wispforest_endec_jankson 0.1.3
	   \-- io_wispforest_endec_netty 0.1.2
	- patchouli 1.21-87-FABRIC
	   \-- fiber 0.23.0-2
	- placeholder-api 2.4.1+1.21
	- playeranimator 2.0.0-alpha1+1.21
	- polylib 2100.0.3-build.159
	   \-- team_reborn_energy 4.1.0
	- polymorph 1.0.6+1.21.1
	- prickle 21.1.6
	- prism 1.0.9
	- puffish_attributes 0.6.0
	- puffish_skills 0.14.1
	- puzzleslib 21.1.22
	- reeses-sodium-options 1.8.0-beta.4+mc1.21.1
	- resourcefullib 3.0.11
	   |-- com_teamresourceful_bytecodecs 1.1.2
	   \-- com_teamresourceful_yabn 1.0.3
	- rightclickharvest 4.4.2+1.21.1
	- roughlyenoughitems 16.0.788
	   \-- error_notifier 1.0.11
	- searchables 1.0.2
	- skinlayers3d 1.7.0
	- smeltingstone 1.21.1-0-fabric
	- smoothchunk 1.21-3.6
	- sodium 0.6.0-beta.4+mc1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   \-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	- sodiumdynamiclights 1.0.9
	- sodiumextras 1.0.5
	- sodiumoptionsapi 1.0.5
	   \-- mixinsquared 0.2.0-beta.6
	- sound_physics_remastered 1.21.1-1.4.6
	- spark 1.10.109
	   \-- fabric-permissions-api-v0 0.3.1
	- starterkit 7.1
	- supplementaries 1.21-3.0.2-alpha
	- terrablender 4.1.0.5
	- travelersbackpack 10.1.3
	- trinkets 3.10.0
	- visuality 0.7.7+1.21
	- visualworkbench 21.1.0
	- weatherdisplay 1.2.0
	- wi_zoom 1.5-MC1.21.1
	- worldedit 7.3.8+6939-7d32b45
	- xaerominimap 24.6.1
	- xaeroworldmap 1.39.0
	- yigd 2.4.11
	   \-- fabric-permissions-api-v0 0.3.1
	- yungsapi 1.21.1-Fabric-5.1.2
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- yungsmenutweaks 1.21.1-Fabric-2.1.1
	   \-- org_reflections_reflections 0.10.2

### Logs

https://pastebin.com/Qq1q6CeS

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
This is an issue with Supplementaries' compat I'm pretty sure, as they are referencing a field that is not present.
@MehVahdJukaar I think this is yours to handle.

**Comment by MehVahdJukaar** [comment]
I'm pretty sure this doesn't happen with latest mod version

**Comment by ChrysanthCow** [comment]
Closing this as not planned bc its not our issue, if this still happens on latest Supplementaries, report there.
