### ISSUE TITLE
SpoiledZ Conflict

### ISSUE THREAD

**Issue by ChristinWhite** [MehVahdJukaar/FarmersDelightRefabricated#102]
### Minecraft version

1.21.1

### Farmer's Delight version

 1.21-2.1.10+refabricated

### Fabric Loader version

0.16.7

### Fabric API version

0.107.0+1.21.1

### Description

I'm getting a crash during startup when I have both Farmer's Delight Refabricated and SpoiledZ enabled. Both run fine without the other enabled. 

SpoiledZ integrates with Fabric Seasons and Serene Seasons, but I get the same behavior with neither, either, or both of them enabled.

I also filed an issue on SpoiledZ's repo: [#18](https://github.com/Globox1997/SpoiledZ/issues/18)

## Environment

Prism Launcher 9.1
Java 21.7.4
macOS Sonoma 14.6.1
M1 (aarch64)

No other mods, shaders or resourcepacks installed other than those in the mod list below.

### Steps to reproduce

1. Enable both SpoiledZ and Farmer's Delight Rebaricated in Prism
2. Attempt to launch the game.
3. Game crashes before the Minecraft window is even started.

### Mod list

SpoiledZ 1.0.10
Cloth Config 15.0.140
GlitchCore 2.1.0.0
Fabric Seasons 2.4.2-BETA+1.21
Serene Seasons 10.1.0.1

### Logs

https://gist.github.com/ChristinWhite/5959b0e5ce6bff0d11f1bff856fb26bf

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
SpoiledZ's problem. They're using a mixin to one of our classes.
