### ISSUE TITLE
All loot tables breaking when CraftTweaker is installed

### ISSUE THREAD

**Issue by Partonetrain** [MehVahdJukaar/FarmersDelightRefabricated#11]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.7

### Forge version

Fabric 0.15.7 (this needs to be changed on the issue template lol)

### Description

All loot tables return empty when FDR is installed alongside CraftTweaker.

### Steps to reproduce

Install CraftTweaker
use `/loot give @p loot minecraft:blocks/cobblestone`
Observe no cobblestone is dropped

See also https://github.com/Fabricators-of-Create/Porting-Lib/issues/74

### Mod list

Amendments
CraftTweaker
FAPI
FDR
Moonlight Lib
Supplementaries
Supplementaries Squared

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
I'll see if Porting Lib has an update that we just aren't using.

**Comment by ChrysanthCow** [comment]
Yup. We were out of date, I'll update the bundled porting lib asap.
