### ISSUE TITLE
Game crash upon startup.

### ISSUE THREAD

**Issue by spzt101** [MehVahdJukaar/FarmersDelightRefabricated#114]
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.3

### Fabric Loader version

0.16.9

### Fabric API version

0.109.0+1.21.1

### Description

Game will crash before seeing anything. This does not happen without the Farmer's Delight mod and the rest of the mods in the provided mod list. Maybe it is conflicting with one of the mods in the set of mods loaded.

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'farmersdelight' at 'vectorwing.farmersdelight.FarmersDelight'!"

### Steps to reproduce

Launch the game.

### Mod list

Fabric Mods: 
		advancednetherite: Advanced Netherite 2.2.0-1.21.1
		aether: The Aether 1.5.1-beta.4
			accessories: Accessories 1.1.0-beta.16+1.21.1
			cumulus_menus: Cumulus 1.1.1
			forgeconfigapiport: Forge Config API Port 21.1.1
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
			mixinextras: MixinExtras 0.5.0-beta.3
			mm_shedaniel: Manningham Mills (shedaniel's fork) 2.4.1
			nitrogen_internals: Nitrogen 1.1.21
		ambientsounds: AmbientSounds 6.1.3
		amplified_nether: Amplified Nether 1.2.6
		appleskin: AppleSkin 3.0.6+mc1.21
		architectury: Architectury 13.0.8
		barteringstation: Bartering Station 21.1.0
		betterdungeons: YUNG's Better Dungeons 1.21.1-Fabric-5.1.3
		betterendisland: YUNG's Better End Island 1.21.1-Fabric-3.1.1
		betterfortresses: YUNG's Better Nether Fortresses 1.21.1-Fabric-3.1.3
		betterjungletemples: YUNG's Better Jungle Temples 1.21.1-Fabric-3.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.21.1-Fabric-5.1.1
		betterstats: Better Statistics Screen 3.13.3+fabric-1.21
		betterwitchhuts: YUNG's Better Witch Huts 1.21.1-Fabric-4.1.1
		chunky: Chunky 1.4.16
		cicada: CICADA 0.9.1+1.21-1.21.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		continuity: Continuity 3.0.0-beta.5+1.21
		copperhopper: Copper Hopper 0.10.0+1.21.1
		crafttweaker: CraftTweaker 21.0.9
			org_reflections_reflections: reflections 0.10.2
		creativecore: CreativeCore 2.12.22
			net_neoforged_bus: bus 7.2.0
		cubes-without-borders: Cubes Without Borders 3.0.0+mc1.21
		debugify: Debugify 1.21.1+1.0
		do_a_barrel_roll: Do a Barrel Roll 3.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.2-beta.4
		dynamic_fps: Dynamic FPS 3.7.6
			net_lostluma_battery: battery 1.3.0
		elementa: Elementa 670
		entityculling: EntityCulling 1.7.1
		essential: Essential 1.3.5.3
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.109.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
		fabricloader: Fabric Loader 0.16.5
		farmersdelight: Farmer's Delight 1.21.1-2.2.3+refabricated
			mm: Manningham Mills 2.3
		ferritecore: FerriteCore 7.0.2-hotfix
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 2.0.2
		friendsandfoes: Friends & Foes 3.0.6
		geckolib: GeckoLib 4 4.7
		glitchcore: GlitchCore 2.1.0.0
			net_jodah_typetools: typetools 0.6.3
		grindenchantments: Grind Enchantments 3.2.2+1.21-rc1
			codec-config-api: Codec config API 2.0.0+1.20.5-rc3
		horseshoes: Horseshoes 1.2.4
		iris: Iris 1.8.0+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jade: Jade 15.8.3+fabric
		jadeaddons: Jade Addons 6.0.3+fabric
		jamlib: JamLib 1.2.2+1.21.1
			blue_endless_jankson: jankson 1.2.3
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.21.0.247
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		leahs-immersive-thunder: Immersive Thunder 1.21.1+1.2.2
		lithium: Lithium 0.14.2-snapshot+mc1.21.1-build.90
		lithostitched: Lithostitched 1.3.4
		merenc: Merge Enchantments 4.1
		mes: Moog's End Structures 1.3.3-1.21-fabric
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mr_beyondenchant: BeyondEnchant 1.5.0
		mr_mob_heads: Mob Heads 1-v.2.7.5
		mr_neoenchant: Neo Enchant+ 5.7.3
		org_jetbrains_annotations: annotations 23.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		owo: oωo 0.12.15+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		puzzleslib: Puzzles Lib 21.1.22
		resourcefulconfig: Resourcefulconfig 3.0.7
		rightclickharvest: Right Click Harvest 4.4.3+1.21.1
		searchables: Searchables 1.0.2
		sereneseasons: SereneSeasons 10.1.0.1
		sodium: Sodium 0.6.0+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		tcdcommons: TCD Commons API 3.12.4+fabric-1.21
		tectonic: Tectonic 2.4.1a
		terrablender: TerraBlender 4.1.0.5
		terralith: Terralith 2.5.6
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		visuality: Visuality 0.7.7+1.21
		wover: WorldWeaver 21.0.13
			wover-biome: WorldWeaver - Biome API 21.0.13
			wover-block: WorldWeaver - Block and Item API 21.0.13
			wover-common: WorldWeaver - Common API 21.0.13
			wover-core: WorldWeaver - Core API 21.0.13
			wover-datagen: WorldWeaver - Datagen API 21.0.13
			wover-events: WorldWeaver - Events API 21.0.13
			wover-feature: WorldWeaver - Feature API 21.0.13
			wover-generator: WorldWeaver - World Generator API 21.0.13
			wover-item: WorldWeaver - Item API 21.0.13
			wover-math: WorldWeaver - Math API 21.0.13
			wover-preset: WorldWeaver - World Preset API 21.0.13
			wover-recipe: WorldWeaver - Recipe API 21.0.13
			wover-structure: WorldWeaver - Structure API 21.0.13
			wover-surface: WorldWeaver - Surface API 21.0.13
			wover-tag: WorldWeaver - Tag API 21.0.13
			wover-ui: WorldWeaver - UI API 21.0.13
		wunderlib: WunderLib 21.0.8
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroplus: XaeroPlus 2.24.5
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			com_github_rfresh2_oldbiomes: OldBiomes 1.0
			net_lenni0451_lambdaevents: LambdaEvents 2.4.2
		xaeroworldmap: Xaero's World Map 1.39.0
		yungsapi: YUNG's API 1.21.1-Fabric-5.1.3

### Logs

https://pastebin.com/JV6ijukP
https://pastebin.com/7BYWD3Lc

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by Poopooracoocoo** [comment]
Why isn't Porting Lib in these logs at all? :/

**Comment by ChrysanthCow** [comment]
Hi, could you please see if this is replicated on Farmer's Delight Refabricated 2.2.5?
We have since moved to a more official Porting Lib build (although with some fixes on our end).

**Comment by ChrysanthCow** [comment]
Please update Fabric Loader to at least 0.16.7. Porting Lib will silently fail if the loader version does not match.
We have since updated the mod with a dependency based on this version, so hopefully less confusion will happen past that point.
