### ISSUE TITLE
Server lag from Farmer's Delight Refabricated / Porting Lib

### ISSUE THREAD

**Issue by DarthLilo** [MehVahdJukaar/FarmersDelightRefabricated#115]
### Minecraft version

1.21

### Farmer's Delight version

2.1.10

### Fabric Loader version

0.16.9

### Fabric API version

0.102.0+1.21

### Description

Ever since we added Farmer's Delight Refabricated to our server it started having extreme TPS drops consistent performance issues.
Investigating further showed that it was a porting lib entity issue and this is the only mod that we use that has porting lib (As far as I know)

![image](https://github.com/user-attachments/assets/9ff15975-b02f-42b0-91d7-abcf2b9aaa76)

Spark profiler log: https://spark.lucko.me/eAwkctRG16

Is this an issue because of the outdated refabricated version? We're trying to debug but can't fully update to 1.21.1 just yet

### Mod list

	- ambientsounds 6.0.5
	- animal_armor_trims 2.0.0
	- ante 1.2
	- appleskin 3.0.6+mc1.21
	- architectury 13.0.8
	- armorstands 2.0.0
	- athena 4.0.1
	- automodpack-bootstrap 1.0.0
	   \-- automodpack 4.0.0-beta20
	        |-- fabric-networking-api-v1 4.3.0+c7469b2119
	        |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	        \-- fabric-resource-loader-v0 1.3.1+5b5275af19
	- balm-fabric 21.0.20
	   \-- kuma_api 21.0.5-SNAPSHOT
	- bclib 21.0.10
	- beautify 1.2.1+1.21
	- beekeeperhut 2.0.1
	- betterdeserttemples 1.21.1-Fabric-4.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.21.1-Fabric-5.1.3
	   \-- org_reflections_reflections 0.10.2
	- betterend 21.0.6
	- betterendisland 1.21.1-Fabric-3.1.1
	   \-- org_reflections_reflections 0.10.2
	- betterfortresses 1.21.1-Fabric-3.1.3
	   \-- org_reflections_reflections 0.10.2
	- betterfurniture 1.21-1.0.5
	- betterjungletemples 1.21.1-Fabric-3.1.2
	   \-- org_reflections_reflections 0.10.2
	- bettermineshafts 1.21.1-Fabric-5.1.1
	   \-- org_reflections_reflections 0.10.2
	- betternether 21.0.9
	- betteroceanmonuments 1.21.1-Fabric-4.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterstats 3.13.3+fabric-1.21
	- betterstrongholds 1.21.1-Fabric-5.1.2
	   \-- org_reflections_reflections 0.10.2
	- betterwitchhuts 1.21.1-Fabric-4.1.1
	   \-- org_reflections_reflections 0.10.2
	- c2me 0.2.0+alpha.11.109+1.21
	   |-- c2me-base 0.2.0+alpha.11.109+1.21
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.109+1.21
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.109+1.21
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.109+1.21
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.109+1.21
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.109+1.21
	   |-- c2me-notickvd 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-allocs 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-math 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.109+1.21
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.109+1.21
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.109+1.21
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.109+1.21
	   |-- c2me-server-utils 0.2.0+alpha.11.109+1.21
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.109+1.21
	   |-- c2me-threading-lighting 0.2.0+alpha.11.109+1.21
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.109+1.21
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- capes 1.5.4+1.21
	- cardinal-components 6.1.2
	   |-- cardinal-components-base 6.1.2
	   |-- cardinal-components-block 6.1.2
	   |-- cardinal-components-chunk 6.1.2
	   |-- cardinal-components-entity 6.1.2
	   |-- cardinal-components-item 6.1.2
	   |-- cardinal-components-level 6.1.2
	   |-- cardinal-components-scoreboard 6.1.2
	   \-- cardinal-components-world 6.1.2
	- carpet 1.4.147+v240613
	- carpet-extra 1.4.148
	- cat_jam 1.3.1
	- chipped 4.0.0
	- chiseled-bookshelf-visualizer 4.0
	   \-- com_github_fracpete_romannumerals4j 0.0.1
	- christmas-delight 1.0-noremandier
	   \-- terraform-wood-api-v1 11.0.0-alpha.1
	- chunky 1.4.16
	- cicada 0.9.1+1.21-1.21.1
	- clean-debug 0.4.8
	- clickthrough 1.21
	- clientsort 1.0.1+1.21
	- cloth-config 15.0.140
	   \-- cloth-basic-math 0.6.1
	- collective 7.87
	- comforts 9.0.3+1.21.1
	   \-- spectrelib 0.17.2+1.21
	        |-- com_electronwill_night-config_core 3.8.0
	        \-- com_electronwill_night-config_toml 3.8.0
	- commonnetworking 1.0.16-1.21
	- connectiblechains 2.4.2+1.21.1
	- controlling 18.0.4
	- copperhopper 0.9.3+1.21
	- copperrails 1.0.4+mc1.21
	- cratedelight 24.11.22-1.21-fabric
	- creativecore 2.12.9
	   \-- net_neoforged_bus 7.2.0
	- cristellib 1.2.8
	   \-- blue_endless_jankson 1.2.3
	- cubes-without-borders 3.0.0+mc1.21
	- cullleaves 3.4.0
	- dark-loading-screen 1.6.14
	- deeperdarker 1.3.2.1
	   \-- customportalapi 0.0.1-beta66-1.21
	- detailab 2.6.3+1.21-fabric
	- disable_custom_worlds_advice 6.0
	- doubledoors 5.9
	- dumplings_delight 1.21-1.2.0+fabric
	   |-- porting_lib_base 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- mm 2.3
	   |    |-- porting_lib_accessors 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_asm 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_attributes 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_common 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_entity 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_fluids 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gui_utils 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_mixin_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_tags 3.0
	   |    \-- porting_lib_transfer 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_config 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_lazy_registration 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   \-- porting_lib_loot 3.1.0-beta+fdrf.1+1.21
	        |-- porting_lib_conditions 3.1.0-beta+fdrf.1+1.21
	        |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	        \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	- durabilitytooltip 1.1.5
	- dynamic_fps 3.7.6
	   \-- net_lostluma_battery 1.3.0
	- dynmap 3.7-SNAPSHOT
	- e4mc_minecraft 5.2.1
	   \-- folk_sisby_kaleido-config 0.3.1+1.3.1
	- eatinganimationid 1.21+1.9.72
	- enhancedblockentities 0.10.2+1.21
	- entity_model_features 2.2.6
	- entity_texture_features 6.2.8
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.7.1
	- explorify 1.6.2
	- fabric-api 0.102.0+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.27+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.16+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-object-builder-api-v1 15.2.0+a551f7a4d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.12+65089712d1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.86+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	- fallingleaves 1.16.2
	- fancymenu 3.2.5
	   |-- com_github_keksuccino_japng 0.5.3
	   \-- com_github_rtyley_animated-gif-lib-for-java animated-gif-lib-1.7
	- farmersdelight 1.21-2.1.10+refabricated
	   |-- mm 2.3
	   |-- porting_lib_base 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- mm 2.3
	   |    |-- porting_lib_accessors 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_asm 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_attributes 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_common 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_entity 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_fluids 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gui_utils 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_mixin_extensions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_tags 3.0
	   |    \-- porting_lib_transfer 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_config 3.1.0-beta+fdrf.1+1.21
	   |    |-- com_electronwill_night-config_core 3.8.0
	   |    |-- com_electronwill_night-config_toml 3.8.0
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_item_abilities 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_blocks 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_level_events 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_lazy_registration 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   |-- porting_lib_loot 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_conditions 3.1.0-beta+fdrf.1+1.21
	   |    |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	   |    \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	   \-- porting_lib_recipe_book_categories 3.1.0-beta+fdrf.1+1.21
	        |-- porting_lib_core 3.1.0-beta+fdrf.1+1.21
	        \-- porting_lib_gametest 3.1.0-beta+fdrf.1+1.21
	- ferritecore 7.0.0
	- feytweaks 1.21-1.2.8
	- flowerymooblooms 2.0.2
	- forgeconfigapiport 21.0.8
	   |-- com_electronwill_night-config_core 3.8.0
	   \-- com_electronwill_night-config_toml 3.8.0
	- freecam 1.3.0+mc1.21
	- friendsandfoes 3.0.6
	- frozenlib 1.9.3-mc1.21.1
	- fzzy_config 0.5.8+1.21
	   |-- blue_endless_jankson 1.2.3
	   |-- fabric-permissions-api-v0 0.3.1
	   \-- net_peanuuutz_tomlkt_tomlkt-jvm 0.3.7
	- glitchcore 2.0.0.3
	   \-- net_jodah_typetools 0.6.3
	- headfix 1.3.1
	- highlight 3.0.0
	- hopobettermineshaft 1.2.7
	- hopobetterruinedportal 1.4.3
	- hopobetterunderwaterruins 1.2.0
	- htm 1.1.13
	   |-- common-protection-api 1.0.0
	   \-- server_translations_api 2.3.1+1.21-pre2
	- immersiveui 0.2.2
	- indypets 1.4.3
	- invview 1.4.15-1.20.5+
	- iris 1.8.0+mc1.21.1
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- items_displayed 1.3
	- jamlib 1.0.9+1.21
	   \-- blue_endless_jankson 1.2.3
	- java 21
	- jmc 1.19.2
	- journeymap 1.21-6.0.0-beta.27
	   |-- ar_com_hjg_pngj 2.1.0
	   \-- journeymap-api-fabric 2.0.0-1.21-SNAPSHOT
	- keybindfixplus 2.0.0
	- konkrete 1.9.9
	- krypton 0.2.8
	   \-- com_velocitypowered_velocity-native 3.3.0-SNAPSHOT
	- ksyxis 1.3.2
	- letmedespawn 1.3.1
	- litematica 0.19.0
	- lithium 0.13.1
	- lolmblv 1.7.0
	- lolmcv 1.5.6
	- make_bubbles_pop 0.3.0-fabric
	- malilib 0.21.2
	   \-- fabric-api-base 0.4.42+6573ed8cd1
	- mavapi 1.2.1
	- mavm 1.3.0
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- mcwholidays 1.1.0
	- mcwlights 1.1.1
	- mcwtrpdoors 1.1.3
	- melody 1.0.10
	- midnightlib 1.6.3
	- mine-spawners 1.4.2
	- minecraft 1.21
	- mo_glass 1.9-MC1.21
	- modelfix 1.21-1.6
	- modmenu 11.0.3
	- monolib 1.4.1
	- moonlight 1.21-2.17.7
	- more_armor_trims 1.4.1-1.21
	- moreculling 1.0.0
	   |-- conditional-mixin 0.6.3
	   \-- mixinsquared 0.2.0
	- moredelight 24.9.27-1.21-fabric
	- mousetweaks 2.26
	- mr_developer_resources 1.6.1
	- mr_dungeons_andtaverns 1-v4.4.4
	- mr_leash_villager 1.1+1.21
	- mr_ls_defaults 1
	- mr_name_tag 1-v.1.1.0
	- mr_terralith_biomesaplings 1.1.3
	- mr_trade_villagerhats 0.1.13
	- mr_vanilla_refresh 1.4.23b
	- mru 1.0.4+1.21+fabric
	- netherportalfix 21.0.2
	- nochatreports 1.21.1-v2.9.1
	- notenoughanimations 1.8.1
	- now-playing 1.5.9
	- obsidianui 0.2.9+mc1.21.1
	- octolib 0.4.2
	   \-- org_yaml_snakeyaml 2.2
	- optigui 2.3.0-beta.6+1.21
	   |-- org_apache_commons_commons-text 1.12.0
	   \-- org_ini4j_ini4j 0.5.4
	- owo 0.12.15+1.21
	   |-- io_wispforest_endec 0.1.5
	   |-- io_wispforest_endec_gson 0.1.3
	   |-- io_wispforest_endec_jankson 0.1.3
	   \-- io_wispforest_endec_netty 0.1.2
	- panorama 1.3.0
	- particular 1.1.1+1.21
	- paxi 1.21.1-Fabric-5.1.2
	   \-- org_reflections_reflections 0.10.2
	- philter 1.3.3+1.21
	- ping-wheel 1.10.0
	- placeholder-api 2.4.1+1.21
	- polydecorations 0.4.2+1.21
	   |-- common-protection-api 1.0.0
	   |-- factorytools 0.3.1+1.21
	   |-- map-canvas-api 0.4.1+1.21
	   \-- sgui 1.6.0+1.21
	- polymer-bundled 0.9.9+1.21
	   |-- polymer-autohost 0.9.9+1.21
	   \-- polymer-blocks 0.9.9+1.21
	- presencefootsteps 1.10.2+1.21
	   \-- kirin 1.20.0+1.21
	- pumpkin_pie 1.0.1+1.21
	- quad 1.2.9
	- rain-grow 1.2
	- reeses-sodium-options 1.8.0-beta.4+mc1.21.1
	- reinfbarrel 2.5.1+1.21
	   \-- reinfcore 4.0.1+1.21
	- reinfchest 3.0.1+1.21
	   \-- reinfcore 4.0.1+1.21
	- reinfshulker 3.1.0+1.21
	   \-- reinfcore 4.0.1+1.21
	- repurposed_structures 7.5.4+1.21-fabric
	- resourcefullib 3.0.11
	   |-- com_teamresourceful_bytecodecs 1.1.2
	   \-- com_teamresourceful_yabn 1.0.3
	- resourcepackoverrides 21.0.0
	- resourcify 1.5.1
	- rightclickharvest 4.3.1+1.21
	- roughlyenoughitems 16.0.788
	   \-- error_notifier 1.0.11
	- rusticdelight 1.0.2
	- ryoamiclights 0.2.11+mc1.21.1
	- sawmill 1.21-1.5.10
	- searchables 1.0.5
	- seeddelight 0.1
	- sereneseasons 10.0.0.6
	   \-- net_jodah_typetools 0.6.3
	- servercore 1.5.4+1.21
	   |-- fabric-permissions-api-v0 0.3.1
	   |-- org_yaml_snakeyaml 2.2
	   |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
	   \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
	- shulkerboxtooltip 5.1.2+1.21
	- simple_copper_pipes 2.0.3
	- sit 1.21-28
	- skinshuffle 2.3.0+1.21
	   |-- com_konghq_unirest-java_standalone 3.11.9
	   |-- commons-validator_commons-validator 1.7
	   |-- org_jsoup_jsoup 1.16.1
	   |-- org_mineskin_java-client 1.2.4-SNAPSHOT
	   \-- spruceui 5.1.0+1.21
	- snowundertrees 2.5.4+1.21.1
	- snuffles 1.2.0+1.21
	- sodium 0.6.0-beta.2+mc1.21.1
	- sodium-extra 0.6.0-beta.3+mc1.21.1
	- sound_physics_remastered 1.21.1-1.4.6
	- soundcontroller 1.1.3
	- sounds 2.2.0+1.21+fabric
	   \-- mixinextras 0.5.0-beta.2
	- spark 1.10.109
	   \-- fabric-permissions-api-v0 0.3.1
	- splinecart 0.1+1.21
	- spyglass_astronomy 1.0.13-mc1.21+
	- status-effect-bars 1.0.6
	- storagedelight 24.9.11-1.21-fabric
	- subtle_effects 1.6.0
	- supermartijn642configlib 1.1.8
	- t_and_t 1.13.2
	- tcdcommons 3.12.4+fabric-1.21
	- tectonic 2.4.1a
	- terralith 2.5.6
	- textile_backup 3.1.3-1.21
	   |-- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
	   |-- org_apache_commons_commons-compress 1.26.1
	   \-- org_tukaani_xz 1.9
	- tia 1.2.1
	- timeoutout 1.0.4+1.20.2
	- titlefixer 1.0+1.21
	- tool_trims 2.2.1
	- travelersbackpack 10.1.3
	- travelerstitles 1.21-Fabric-5.0.0
	   \-- org_reflections_reflections 0.10.2
	- treeharvester 9.1
	- trinkets 3.10.0
	- ubesdelight 0.2.3
	- universal-graves 3.4.4+1.21
	   |-- common-protection-api 1.0.0
	   |-- polymer-core 0.9.14+1.21.1
	   |    |-- polymer-networking 0.9.14+1.21.1
	   |    |    \-- polymer-common 0.9.14+1.21.1
	   |    |         \-- packet_tweaker 0.5.5+1.21
	   |    \-- polymer-registry-sync-manipulator 0.9.14+1.21.1
	   |-- polymer-resource-pack 0.9.14+1.21.1
	   |    \-- polymer-common 0.9.14+1.21.1
	   |         \-- packet_tweaker 0.5.5+1.21
	   |-- polymer-virtual-entity 0.9.14+1.21.1
	   |    \-- polymer-common 0.9.14+1.21.1
	   |         \-- packet_tweaker 0.5.5+1.21
	   |-- predicate-api 0.5.1+1.21
	   |-- server_translations_api 2.3.1+1.21-pre2
	   \-- sgui 1.6.0+1.21
	- universal_shops 1.7.1+1.21
	   |-- common-economy-api 1.1.1
	   |-- common-protection-api 1.0.0
	   |-- server_translations_api 2.3.1+1.21-pre2
	   \-- sgui 1.6.0+1.21
	- valhelsia_core 1.1.2
	- valhelsia_furniture 1.1.0
	- vanityslots 1.4.2+1.21
	- variantsandventures 1.0.6
	- vcinteraction 1.21.1-1.0.8
	- visuality 0.7.7+1.21
	- voicechat 1.21.1-2.5.26
	- waystones 21.1.5
	- wi_zoom 1.5-MC1.21
	- worldedit 7.3.8+6939-7d32b45
	- wover 21.0.11
	   |-- wover-biome 21.0.11
	   |-- wover-block 21.0.11
	   |-- wover-common 21.0.11
	   |-- wover-core 21.0.11
	   |-- wover-datagen 21.0.11
	   |-- wover-events 21.0.11
	   |-- wover-feature 21.0.11
	   |-- wover-generator 21.0.11
	   |-- wover-item 21.0.11
	   |-- wover-math 21.0.11
	   |-- wover-preset 21.0.11
	   |-- wover-recipe 21.0.11
	   |-- wover-structure 21.0.11
	   |-- wover-surface 21.0.11
	   |-- wover-tag 21.0.11
	   |-- wover-ui 21.0.11
	   \-- wunderlib 21.0.5
	- xp_storage 1.6+1.21
	- xp_storage_trinkets 1.0.2+1.21
	- yet_another_config_lib_v3 3.6.1+1.21-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.21.1-Fabric-5.1.3
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- yungsbridges 1.21.1-Fabric-5.1.1
	   \-- org_reflections_reflections 0.10.2
	- yungsextras 1.21.1-Fabric-5.1.1
	   \-- org_reflections_reflections 0.10.2

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Not a Porting Lib issue. It just looks like Porting Lib bc they wrap the tick method.

This seems to be an issue with an advancement checking for NBT consistently. Typically, you don't want to do this.
