### ISSUE TITLE
Waterlogged Skillets

### ISSUE THREAD

**Issue by Chaosticloki** [MehVahdJukaar/FarmersDelightRefabricated#116]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1-2.2.0+

### Fabric Loader version

0.16.9

### Fabric API version

0.92.2+1.20.1.jar

### Description

Hi I'm currently testing this mod and have run into the unusual aspect of every skillet that's generated into the world is water logged, its not a breaking game bug and it just takes a bucket to un water log it but I figured I would let you know its happening

### Mod list

[Sculked Magpie Origin (by LunaNight134)](https://www.curseforge.com/minecraft/mc-mods/sculked-magpie-origin)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Farmer's Respite (Fabric) (by JustoPlayzz_)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
[Chested Companions (by khajiitos)](https://www.curseforge.com/minecraft/mc-mods/chested-companions)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Nether's Delight (Fabric) (by StevePlayzz_)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight-fabric)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[[Let's Do] Vinery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery)
[Origins (Fabric) (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins)
[YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[Chef's Delight [Fabric] (by redstone3game)](https://www.curseforge.com/minecraft/mc-mods/chefs-delight-fabric)
[Critters and Companions (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/critters-and-companions)
[Friends & Foes (Fabric/Quilt) (Copper Golem,Glare,Crab,Moobloom,Iceologer,Rascal,Tuff Golem,Wildfire,Illusioner) (by Faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[YUNG's Better Jungle Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples-fabric)
[Quad (by LieOnLion)](https://www.curseforge.com/minecraft/mc-mods/quad)
[Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
[Just Mob Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)
[Chalk (Fabric): Colorful Addon (by DaFuqsy)](https://www.curseforge.com/minecraft/mc-mods/chalk-fabric-colorful-addon)
[[Let's Do] API (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/do-api)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Polymer (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/polymer)
[Origins++ (by QuantumXenon)](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[NutritionZ (by xR4YM0ND)](https://www.curseforge.com/minecraft/mc-mods/nutritionz)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Patchouli (Fabric/Quilt) (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Beautify: Refabricated (by Suel_ki)](https://www.curseforge.com/minecraft/mc-mods/beautify-refabricated)
[Mythic Mounts (by chirpycricket__)](https://www.curseforge.com/minecraft/mc-mods/mythic-mounts)
[Legacy: [Let's Do] Candlelight (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-candlelight)
[Just Player Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
[Mob Lassos [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/mob-lassos)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Backpacked (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/backpacked)
[Legacy: [Let's Do] Bakery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-bakery)
[Better Villages - Fabric (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-fabric)
[Library Ferret - Fabric (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-fabric)
[Amendments (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/amendments)
[Waystones (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
[In-Game Brewing Guide (by THE_PINPAL)](https://www.curseforge.com/minecraft/texture-packs/in-game-brewing-guide)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[[Let's Do] Beachparty (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-beachparty)
[YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric)
[Night Lights (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/nightlights)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Chalk (Fabric) (by DaFuqsy)](https://www.curseforge.com/minecraft/mc-mods/chalk-fabric)
[Lootr (Fabric) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric)
[Framework (Fabric) (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework-fabric)
[More Chests Variants (MCV) (by LieOnLion)](https://www.curseforge.com/minecraft/mc-mods/more-chest-variants-lieonlion)
[Plushie Mod (by Link4real)](https://www.curseforge.com/minecraft/mc-mods/plushie-mod)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[[Let's Do] Meadow (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow)
[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[Friends&Foes - Flowery Mooblooms (Fabric/Quilt) (by Faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-flowery-mooblooms-fabric)
[More Axolotl Variants API (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavapi)
[More Mob Variants (by nyuppo)](https://www.curseforge.com/minecraft/mc-mods/more-mob-variants)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Sodium (by JellySquid)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Universal Graves (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/universal-graves)
[Farmer's Delight Refabricated (by MerchantPug)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated)
[More Axolotl Variants Mod (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavm)
[YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric)
[Motschen's Better Leaves (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves)
[Leaves Be Gone [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Goblin Traders [Fabric] (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblintraders-fabric)
[Forge Config API Port (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Origins: Classes (by Apace)](https://www.curseforge.com/minecraft/mc-mods/origins-classes)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Mhm, this was a bug fixed in the og Farmer's Delight. I'll fix this when I can.
