### ISSUE TITLE
Fabric 1.21.1 (PortingLib) error in console - Could not decode GlobalLootModifier

### ISSUE THREAD

**Issue by NeoFolia** [MehVahdJukaar/FarmersDelightRefabricated#117]
### Minecraft version

1.21.1

### Farmer's Delight version

FarmersDelight-1.21.1-2.2.3+refabricated.jar

### Fabric Loader version

fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar

### Fabric API version

fabric-api-0.110.0+1.21.1.jar

### Description

https://mclo.gs/0T7EWXf

### Steps to reproduce

https://mclo.gs/0T7EWXf

### Mod list

artifacts
trinkets
farmer's delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Artifacts seems to reimplement the exact same NeoForge system.
The solution would be for Artifacts to use Fabric's Loot system, please bring it up to them.
