### ISSUE TITLE
game crashes when skillet is present in game

### ISSUE THREAD

**Issue by sleeplessKomodo** [MehVahdJukaar/FarmersDelightRefabricated#119]
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.3

### Fabric Loader version

0.16.9

### Fabric API version

0.110.0+1.21.1

### Description

This crash first occurred after a skillet was placed down on the stove. It was crafted without issue. Now, after this crash, if I try to run the game again, the game crashes, but if I disable this mod, the crashes stop. 

The cooking pot can be placed without issue, so this crash seems to be linked to the skillet somehow, although there could be confounding variables. 

### Steps to reproduce

1. With the farmers delight stove already placed, craft/obtain a skillet. 
2. Place the skillet via sneaking and placing the skillet on the stove. 
3. The game crashes instantly. 

### Mod list

- Accessories [1\.1\.0\-beta\.16\+1\.21\.1]
- ActuallyHarvest [1\.1\.1\.1]
- AmbientSounds [6\.1\.3]
- Amendments [1\.21\-1\.2\.19]
- Animal Feeding Trough [1\.1\.2\+1\.21\.1]
- AppleSkin [3\.0\.6\+mc1\.21]
- Architectury [13\.0\.8]
- Back\-burner [1\.4\.1\+1\.21]
- Bad Packets [0\.8\.1]
- Balm [21\.0\.20]
- Better Advancements [0\.4\.3\.21]
- Better Babies [0\.7\.13]
- Better Mount HUD [1\.2\.4]
- Better Name Visibility [1\.1]
- Better Third Person [1\.9\.0]
- BetterF1 [1\.0]
- Bookshelf [21\.1\.13]
- Brainier Bees [1\.6]
- CICADA [0\.9\.1\+1\.21\-1\.21\.1]
- Cardinal Components API [6\.1\.1]
- Carry On [2\.2\.2]
- Cloth Config v15 [15\.0\.140]
- Cobweb [1\.1\.3]
- Collective [7\.87]
- Concurrent Chunk Management Engine [0\.3\.0\+alpha\.0\.299\+1\.21\.1]
- Configured [2\.6\.0]
- Continuity [3\.0\.0\-beta\.5\+1\.21]
- Cooking for Blockheads [21\.1\.3]
- CoroUtil [1\.21\.0\-1\.3\.7]
- CraftedCore [5\.6]
- Crafting Tweaks [21\.1\.3]
- CreativeCore [2\.12\.23]
- CustomSkinLoader [14\.21\.2]
- Cut Through [21\.1\.0]
- Dark Loading Screen [1\.6\.14]
- Data API [1\.6\.3]
- Death Count [1\.0]
- Debugify [1\.21\.1\+1\.0]
- Detail Armor Bar [2\.6\.3\+1\.21\.1\-fabric]
- DropConfirm [3\.0\.0]
- Dynamic FPS [3\.7\.6]
- Dynamic Lights [1\.8\.4\+mod]
- Easy Anvils [21\.1\.0]
- Easy Magic [21\.1\.0]
- Easy Mob Farm [8\.6\.2]
- Enchanted Vertical Slabs [2\.3\.1]
- EnchantmentDescriptions [21\.1\.5]
- Enhanced Block Entities [0\.10\.2\+1\.21]
- Entity Model Features [2\.2\.6]
- Entity Texture Features [6\.2\.8]
- EntityCulling [1\.7\.1]
- Expanded Storage [14\.2\.0]
- Fabric API [0\.110\.0\+1\.21\.1]
- Fabric Language Kotlin [1\.13\.0\+kotlin\.2\.1\.0]
- Falling Leaves [1\.16\.4]
- Farmer's Delight [1\.21\.1\-2\.2\.3\+refabricated]
- Faster Random [5\.1\.0]
- Forge Config API Port [21\.1\.2]
- Fzzy Config [0\.5\.8\+1\.21]
- Gaming Furniture [0\.3\.0]
- GetDown [1\.3\.0]
- Handcrafted [4\.0\.2]
- Hang Glider [21\.1\.0]
- Hide Experimental Warning [1\.2]
- Horses stay still\! [1\.0\.1]
- Immersive Aircraft [1\.1\.5\+1\.21\.1]
- Immersive Lanterns [1\.0\.4]
- Inventory Profiles Next [2\.1\.0]
- Iris [1\.8\.1\+mc1\.21\.1]
- Iron Ladders [2\.5\.02]
- ItemSwapper [0\.7\.3]
- Joy of Painting [1\.21\.1\-1\.0\.1]
- Just Enough Items [19\.21\.0\.247]
- Keybind Fix [1\.0\.1]
- Keybind Fix Plus [2\.0\.0]
- Krypton [0\.2\.8]
- Leaves Be Gone [21\.1\.0]
- Lithium [0\.14\.2\-snapshot\+mc1\.21\.1\-build\.90]
- Living Things [1\.21\.1\-2\.2\.0]
- Load My F\*\*\*ing Tags [1\.0\.4\+1\.21]
- MRU\-1\.0\.4\+1\.21\+fabric
- Macaw's Bridges [3\.0\.0]
- Macaw's Doors [1\.1\.1]
- Macaw's Lights and Lamps [1\.1\.1]
- Medieval Weapons [1\.5\.0]
- Mo Glass [1\.10\-MC1\.21\.1]
- Mod Menu [11\.0\.3]
- Model Gap Fix [1\.21\-1\.6]
- ModernFix [5\.19\.5\+mc1\.21\.1]
- Moonlight Lib [1\.21\-2\.17\.9]
- More Delight [24\.09\.27\-1\.21\-fabric]
- More Slabs Stairs & Walls [4\.1\.1]
- More Stick Variants \(MStV\) [1\.2\.3]
- Mouse Tweaks [2\.26]
- Name Tag Tweaks [3\.8]
- Neat [1\.21\-40\-FABRIC]
- Nemo's More Ladder Variants \(MStV\) [1\.0\.3]
- NiftyCarts [21\.0\.1]
- NoRealmsButton [1\.1\.0]
- NoRecipeBook [3\.4\+1\.21\.1]
- Noisium [2\.3\.0\+mc1\.21\-1\.21\.1]
- PPeTP [1\.2\.0]
- Packet Fixer [1\.4\.2]
- Palladium [1\.0\.9\.5]
- Particle Core [0\.2\.4\+1\.21]
- Persistent Parrots [1\.0]
- Physics Mod [3\.0\.20]
- Placeholder API [2\.4\.1\+1\.21]
- Presence Footsteps [1\.10\.2\+1\.21]
- PrickleMC [21\.1\.6]
- Private Horses [1\.21\-0\.0\.1]
- Puzzles Lib [21\.1\.22]
- Reese's Sodium Options [1\.8\.0\+mc1\.21\.3]
- Refined Advancements [1\.0\.4a]
- Resourceful Lib [3\.0\.11]
- Seamless Loading Screen [2\.2\.1\+1\.21]
- Show Me Your Skin\! [1\.11\.3\+1\.21]
- Sit [1\.21\-28]
- Small Ships [2\.0\.0\-b2\.1]
- Sodium [0\.6\.1\+mc1\.21\.1]
- Sodium Dynamic Lights [1\.0\.9]
- Sodium Options API [1\.0\.8]
- Sound Physics Remastered [1\.21\.1\-1\.4\.6]
- Sounds\-2\.2\.0\+1\.21\+fabric
- Stoneworks [21\.1\.0]
- Tectonic [2\.4\.1a]
- Terralith [2\.5\.6]
- ToadLib [1\.1\.6]
- Traveler's Backpack [10\.1\.3]
- TxniLib [1\.0\.2]
- Vanilla\* Horses [1\.0\.1\+1\.21\.1]
- Walkers [5\.4]
- Waystones [21\.1\.5]
- What Are They Up To [1\.21\.0\-1\.1\.3]
- WorldEdit [7\.3\.8\+6939\-7d32b45]
- Xaero's Minimap [24\.6\.1]
- Xaero's World Map [1\.39\.0]
- XaeroPlus [2\.24\.5]
- YOSBR [0\.1\.2]
- YUNG's API [1\.21\.1\-Fabric\-5\.1\.3]
- YUNG's Better Mineshafts [1\.21\.1\-Fabric\-5\.1\.1]
- YUNG's Better Nether Fortresses [1\.21\.1\-Fabric\-3\.1\.3]
- YUNG's Extras [1\.21\.1\-Fabric\-5\.1\.1]
- YetAnotherConfigLib [3\.6\.1\+1\.21\-fabric]
- You're in Grave Danger [2\.4\.11]
- Zoomify [2\.14\.2\+1\.21\.1]
- disablefrontperspective [1\.0\.0\-fabric\+0\.100\.1\+1\.21]
- libIPN [6\.2\.0]
- oωo [0\.12\.15\+1\.21]
- wthit [12\.4\.3]

### Logs

[latest.log](https://github.com/user-attachments/files/17985986/latest.log)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Fixed in 2.2.4.
