### ISSUE TITLE
Invoke base hover text in ConsumeableItems 

### ISSUE THREAD

**Issue by TheDeathlyCow** [MehVahdJukaar/FarmersDelightRefabricated#12]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.7

### Forge version

0.15.7

### Description

Hello,

I'm the developer of the mods Frostiful and Scorchful. These mods both have integrations with Farmer's Delight food items for things related to temperature and thirst. These integrations work through a series of tags and (should) automatically insert a tooltip text on selected items and grant effects when they're consumed. In the old port, this works fine. However, in this version of the mod, the `ConsumableItem` class fully overrides the `appendHoverText` method of `Item`, which means that the tooltip does not show up. The effects are still applied, as that hooks into the `minecraft:consume_item` advancement trigger which is properly invoked here, it's just the tooltip text that does not show up. 

This can be fixed with a simple call of `super.appendHoverText(stack, level, tooltip, isAdvanced)` somewhere in `ConsumableItem#appendHoverText`.

### Mod list

* Fabric API 
* Mod Menu
* Cardinal Components API 
* Cloth Config
* Thermoo
* Scorchful
* Farmer's Delight Refabricated

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Fixed in 2.0.8.

**Comment by ChrysanthCow** [comment]
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/81167232/a015c145-5000-4cdd-85d7-19687cef36eb)
