### ISSUE TITLE
Supplementaries and Amendments Incompatibility?

### ISSUE THREAD

**Issue by PrinceDrowsy** [MehVahdJukaar/FarmersDelightRefabricated#121]
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.6

### Fabric Loader version

Quilt 0.27.0

### Fabric API version

Quilted Fabric API 11.0.0-alpha.3+0.102.0-1.21

### Description

The game crashes before even loading when I try to open it in the launcher

### Mod list

https://pastebin.com/4r6f0vnV
![image](https://github.com/user-attachments/assets/52d18cb2-3fe9-447b-9dbb-1645634ff44f)

### Logs

https://pastebin.com/4r6f0vnV

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by PrinceDrowsy** [comment]
Updated to the latest versions of Supplementaries and Amendments, still getting an error when they're in with Farmer's Delight

**Comment by ChrysanthCow** [comment]
Likely a Quilt Loader issue.

They might not be upstream with Fabric Loader 0.16.7 or above, of which is required by Porting Lib to load.
