### ISSUE TITLE
Incompatibility with some Farmers Delight addons

### ISSUE THREAD

**Issue by Cyan476** [MehVahdJukaar/FarmersDelightRefabricated#126]
### Minecraft version

1.20.1

### Farmer's Delight version

1.4.3

### Fabric Loader version

0.16.2

### Fabric API version

0.92.2

### Description

When loading Farmers Delight with Expanded Delight, Ends Delight, Cultural Delights and Brewin and Chewin, game instantly crashes

### Steps to reproduce

1. Install Farmers Delight
2. Install Expanded Delight, Ends Delight, Cultural Delights and Brewin and Chewin
3. Load game
4. Game crashes

### Mod list

a_man_with_plushies: A Man With Plushies 4.2.0
		ad_astra: Ad Astra 1.15.3
		additionallanterns: Additional Lanterns 1.1.1a
		all_the_fan_made_discs: All The Fan Made Discs 0.5.6
		animation_overhaul: Animation Overhaul 1.3.1
			player-animator: Player Animator 1.0.2-rc1+1.20
		appleskin: AppleSkin 2.5.1+mc1.20
		archers: Archers (RPG Series) 1.2.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
			ranged_weapon_api: RangedWeaponAPI 1.1.0+1.20.1
			structure_pool_api: Structure Pool API 1.0+1.20.1
		architectury: Architectury 9.2.14
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		azurelib: AzureLib 2.0.39
		azurelibarmor: AzureLib Armor 2.0.12
		bbs: Better Block Sounds 1.20.1-0.1.3
		bedrockify: BedrockIfy 1.9.1+mc1.20
			panorama_screens: Panorama Screens 1.0+fabric+mc1.20
		bedspreads: Bedspreads 6.2.0+1.20.1
		better_christmas_chests: Better Christmas Chests 1.0.0
		betterarcheology: Better Archeology 1.2.1-1.20.1
		betterclouds: Better Clouds 1.3.23+1.20.1-fabric
		bettercombat: Better Combat 1.8.6+1.20.1
		betterf3: BetterF3 7.0.2
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
		boathud: BoatHud 1.1.4
		boathud_extended: BoatHUD (Extended) 1.0.0
		boatiview: Boat Item View Fabric 0.0.5
		botarium: Botarium 2.3.4
			team_reborn_energy: Energy 3.0.0
		bounced: Bounced! 4.1.3
		bountiful: Bountiful 6.0.4+1.20.1
		brewinandchewin: Brewin And Chewin 3.0.6+1.20.1
			mm: Manningham Mills 2.3
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.13
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.13
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.13
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.13
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.13
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.13
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.13
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.13
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.13
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.13
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.13
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.13
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.13
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.13
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.13
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.13
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.13
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.13
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.13
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.13
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.13
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		camerapture: Camerapture 1.6.4
			io_github_darkxanter_webp-imageio: webp-imageio 0.3.2
		catloaf: Cat Loaf 1.1.0
		centeredplants: CenteredPlants 2.0
		chatanimation: ChatAnimation 1.0.5
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		clock_hud: Clock HUD 2.1.0-mc1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		clutter: Clutter 1.20-0.6.0
		collective: Collective 7.87
		coloredfishingline: Colored Fishing Line 1.20-1.0.2
		colorful_hex: Colorful HEX 1.1.0
		comforts: Comforts 6.4.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		continuity: Continuity 3.0.0+1.20.1
		convenientdecor: Convenient Decor 0.4.3
			omega-config: OmegaConfig 1.4.0+1.20.1
		cornexpansion: [Let's Do Addon] Corn Expansion 1.0.1
		croptopia: Croptopia 3.0.3
		culturaldelights: Cultural Delights Fabric 1.0.5+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		custompaintings: Custom Paintings 2.1.0
		customworldicons: Custom World Icons 1.1.0-1.20.x
		dailyshop: Daily Shop 1.0.2
		dark-loading-screen: Dark Loading Screen 1.6.14
		debugify: Debugify 1.20.1+2.0
		decorative_gaming_consoles: Decorative Gaming Consoles 1.1.0
		detailab: Detail Armor Bar 2.6.3+1.20.1-fabric
		doapi: [Let's Do] API 1.2.15
		draggable_lists: Draggable Lists 1.0.1
		dsurround: Dynamic Surroundings 0.3.3
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
		durabilitytooltip: Durability Tooltip 1.1.5
		dynamic_fps: Dynamic FPS 3.1.0
		eatinganimationid: Eating Animation 1.20+1.9.61
		edgelesschatscreen: Edgeless Chat Screen 1.1.5
		effective: Effective 2.3.2-1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
			lodestone: Lodestone 1.20.1-1.6.2.3f-fabric
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
			porting_lib_blocks: Porting Lib Blocks 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_core: Porting Lib Core 2.3.4+1.20.1
			porting_lib_data: Porting Lib Data 2.3.4+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
			porting_lib_items: Porting Lib Items 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.3.4+1.20.1
				porting_lib_model_materials: Porting Lib Model Materials 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_models: Porting Lib Models 2.3.4+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
			satin: Satin 1.14.0
		elegantia: Elegantia 0.0.1-beta+1.20-1.20.1
		elytratrims: Elytra Trims 3.5.4
			conditional-mixin: conditional mixin 0.6.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		emogg: emogg 2.0.1+1.20-1.20.1
			suggestions-api: SuggestionsAPI 1.0.6+1.20-1.20.4-fabric
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
		ends_delight: End's Delight refabricated-1.20.1-2.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.8
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		epherolib: EpheroLib 1.2.0
		evs: Enchanted Vertical Slabs 2.2.1-backport1.20.1
		expandeddelight: Expanded Delight 0.3.2
		explosiveenhancement: Explosive Enhancement 1.2.2-1.20.x
		extraspellattributes: Extra RPG Attributes 1.2.16
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.2
		falling-block-particles: Falling Block Particles 1.0.1
		fallingleaves: Falling Leaves 1.15.6
		fan_cake: FanCake ${version}
		fancydyes: Fancy Dyes 2.2.2
		farm_and_charm: [Let's Do] Farm & Charm 1.0.4
			blue_endless_jankson: jankson 1.2.3
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		fastmove: FastMove - Parkour Movement 1.0.8
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		fish_tank: Fish Tanks 1.0.2
		fishontheline: Fish On The Line 3.4
		flash: Flash 2.1.1
			com_github_krlite_equator-v2_animation: Animation 2.6.4-mc1.20
			com_github_krlite_equator-v2_math: Math 2.6.4-mc1.20
			com_github_krlite_equator-v2_visual: Visual 2.6.4-mc1.20
		flow: Flow 2.2.0+1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.1
		fps: FPS Monitor 1.20-1.3.0-Fabric
		framework: Framework 0.7.12
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		friendsandfoes: Friends & Foes 3.0.6
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		ftblibrary: FTB Library 2001.2.1
		ftbquests: FTB Quests 2001.4.4
		ftbteams: FTB Teams 2001.3.0
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		glasses: glasses 1.2.1
		glowingbanners: Glow Banners 1.3.2
		goop: Goop Technology 1.20.x-0.3
		guarding: Guarding 2.4.0
			scribe: Scribe 1.20.1-0.5.0-alpha
		headed: Headed 1.1.3-1.20
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
		hex_banners: Hex Banners 1.0
		highlight: Highlight 2.0.1
		hswf3: Hide Scoreboard When F3 1.0.0
		iceberg: Iceberg 1.1.25
		ichunutil: iChunUtil 1.0.0
		immediatelyfast: ImmediatelyFast 1.3.2+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		immersive_melodies: Immersive Melodies 0.3.0+1.20.1
		immersiveui: ImmersiveUI 0.2.2
		indium: Indium 1.0.34+mc1.20.1
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jewelry: Jewelry (RPG Series) 1.3.7+1.20.1
		jobsaddon: JobsAddon 1.1.6
		kambrik: Kambrik 6.1.1+1.20.1
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		laserbridges: LaserBridges 1.20.1-2-fabric
		lavajava: Lava Java 0.4.4
		lavasand: LavaTurnsSandIntoGlass 1.20.1-0-fabric
		lazydfu: LazyDFU 0.1.3
		levelz: LevelZ 1.4.13
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lightmanscurrency: Lightman's Currency 1.20.1-1.0.2.4
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.13.33
		more_armor_trims: More Armor Trims 1.4.1-1.20.1
		mr_colorful_trims: Colorful Trims 1.6
		mr_craftablegunpowder: Craftable Gunpowder 1.1
		mr_hero_proof: Hero Proof 5.2.1
		mr_swap_item: Swap Item 1.1.1
		mru: Mineblock's Repeated Utilities 1.0.4+1.20.1+fabric
		mythicupgrades: Mythic Upgrades 4.2.0+mc1.20.1
		necronomicon: Necronomicon 1.6.0
		octolib: OctoLib 0.4.2
			org_yaml_snakeyaml: snakeyaml 2.2
		owo: oωo 0.11.2+1.20
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		puzzleslib: Puzzles Lib 8.1.25
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		quad: Quad 1.2.3
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		shutter: Shutter 2.0.5-fabric-1.20.4
		sleepwarp: SleepWarp 2.2.0_rc1+1.20.1
		smoke_signals: Smoke Signals 1.0
		sodium: Sodium 0.5.11+mc1.20.1
		sootychimneys: Sooty Chimneys for Fabric 1.1.0
		sounds: Sounds 2.2.1+1.20.1+fabric
			mixinextras: MixinExtras 0.5.0-beta.2
		spell_engine: Spell Engine 0.15.11+1.20.1
		spell_power: Spell Power Attribute 0.12.0+1.20.1
		spellbladenext: Spellblades and Such 2.0.1+1.20.1
		spelunker: Spelunker 1.5.3-mc1.20
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
		stackrefill: Stack Refill 4.5
		stairdoors: StairDoors Extended 1.0.0
		status-effect-bars: Status Effect Bars 1.0.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		supplementaries: Supplementaries 1.20-3.1.10
		tlskincape: TLSkinCape 1.32
		trimmable_tools: Trimmable Tools 2.0.5
		trinkets: Trinkets 3.7.2
		vc_gliders: Gliders 1.1.6
			palladiumcore: PalladiumCore 1.20-2.0.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.6

### Logs

https://mclo.gs/F6WWchR

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
You are using the old port. Update to this port found at...
https://modrinth.com/mod/farmers-delight-refabricated
https://curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
