### ISSUE TITLE
与某些模组不兼容

### ISSUE THREAD

**Issue by LTGVE** [MehVahdJukaar/FarmersDelightRefabricated#127]
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.7

### Fabric Loader version

0.16.9

### Fabric API version

0.110.0+1.21.1

### Description

很抱歉使用中文来提交Issue
以下是我对崩溃发生的描述:
我是在服务端上加载它的
当这个模组与*CardBoard*加载时,它就会崩溃
我已确定是它与CardBoard产生的崩溃,与CardBoard的前置模组不会产生冲突
<a href="https://cardboardpowered.org/download/">*CardBoard*</a>

### Steps to reproduce

1.在mods文件夹里添加CardBoard与FarmersDelightRefabricated
2.启动服务端

### Mod list

        - cardboard 3
           |-- io_leangen_geantyref_geantyref 1.3.16
           \-- net_md-5_specialsource 1.11.2
        - fabric-api 0.110.0+1.21.1
           |-- fabric-api-base 0.4.42+6573ed8c19
           |-- fabric-api-lookup-api-v1 1.6.70+b559734419
           |-- fabric-biome-api-v1 13.0.30+be1ed2d719
           |-- fabric-block-api-v1 1.0.22+0af3f5a719
           |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
           |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
           |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
           |-- fabric-command-api-v1 1.2.49+f71b366f19
           |-- fabric-command-api-v2 2.2.28+6ced4dd919
           |-- fabric-commands-v0 0.2.66+df3654b319
           |-- fabric-content-registries-v0 8.0.18+b559734419
           |-- fabric-convention-tags-v1 2.1.2+7f945d5b19
           |-- fabric-convention-tags-v2 2.9.2+e60e56d419
           |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
           |-- fabric-data-attachment-api-v1 1.4.0+da19b51a19
           |-- fabric-data-generation-api-v1 20.2.24+16c4ae2519
           |-- fabric-dimensions-v1 4.0.0+6fc22b9919
           |-- fabric-entity-events-v1 1.7.0+2122d82819
           |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
           |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
           |-- fabric-item-api-v1 11.1.1+d5debaed19
           |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
           |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
           |-- fabric-keybindings-v0 0.2.45+df3654b319
           |-- fabric-lifecycle-events-v1 2.5.0+01d9a51c19
           |-- fabric-loot-api-v2 3.0.15+3f89f5a519
           |-- fabric-loot-api-v3 1.0.3+3f89f5a519
           |-- fabric-message-api-v1 6.0.13+6573ed8c19
           |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
           |-- fabric-networking-api-v1 4.3.0+c7469b2119
           |-- fabric-object-builder-api-v1 15.2.1+40875a9319
           |-- fabric-particles-v1 4.0.2+6573ed8c19
           |-- fabric-recipe-api-v1 5.0.13+6508971219
           |-- fabric-registry-sync-v0 5.2.0+34f5d91419
           |-- fabric-renderer-api-v1 3.4.0+c705a49c19
           |-- fabric-renderer-indigo 1.7.0+c705a49c19
           |-- fabric-renderer-registries-v1 3.2.68+df3654b319
           |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
           |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
           |-- fabric-rendering-v0 1.1.71+df3654b319
           |-- fabric-rendering-v1 5.0.5+df16efd019
           |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
           |-- fabric-resource-loader-v0 1.3.1+5b5275af19
           |-- fabric-screen-api-v1 2.0.25+8b68f1c719
           |-- fabric-screen-handler-api-v1 1.3.88+b559734419
           |-- fabric-sound-api-v1 1.0.23+6573ed8c19
           |-- fabric-transfer-api-v1 5.4.2+95bead5f19
           \-- fabric-transitive-access-wideners-v1 6.2.0+45b9699719
        - fabricloader 0.16.9
        - farmersdelight 1.21.1-2.2.7+refabricated
           |-- mm 2.3
           |-- porting_lib_base 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- com_electronwill_night-config_core 3.8.0
           |    |-- com_electronwill_night-config_toml 3.8.0
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- mm 2.3
           |    |-- porting_lib_accessors 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_asm 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_attributes 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_blocks 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_common 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_entity 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_extensions 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_fluids 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_gui_utils 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_level_events 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_mixin_extensions 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_tags 3.0
           |    \-- porting_lib_transfer 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_config 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- com_electronwill_night-config_core 3.8.0
           |    |-- com_electronwill_night-config_toml 3.8.0
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_item_abilities 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_blocks 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_level_events 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_lazy_registration 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           |-- porting_lib_loot 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- mixinextras 0.5.0-beta.3
           |    |-- porting_lib_conditions 3.1.0-beta.47.hotfix.1+1.21.1
           |    |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
           |    \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
           \-- porting_lib_recipe_book_categories 3.1.0-beta.47.hotfix.1+1.21.1
                |-- mixinextras 0.5.0-beta.3
                |-- porting_lib_core 3.1.0-beta.47.hotfix.1+1.21.1
                \-- porting_lib_gametest 3.1.0-beta.47.hotfix.1+1.21.1
        - icommon-bundle bundle
           \-- icommon 1.21
        - java 21
        - minecraft 1.21.1

### Logs
https://mclo.gs/jRcDaX9

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Cardboard is known for being quite faulty towards other mods. I don't think this is something on our end.
