### ISSUE TITLE
java.lang.NullPointerException: Mod icon for porting_lib is null somehow (should be filled with default in this case)

### ISSUE THREAD

**Issue by Delfonso** [MehVahdJukaar/FarmersDelightRefabricated#13]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.9

### Fabric Loader version

0.15.7

### Fabric API version

0.92.0

### Description

im crashing when porting_lib comes up in mod menu

### Steps to reproduce

1. be in mod menu
2. show libraries
3. search or scroll to porting lib

### Mod list

crash report:
[crash-2024-03-30_13.01.02-client.txt](https://github.com/MehVahdJukaar/FarmersDelight/files/14812912/crash-2024-03-30_13.01.02-client.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
This is a porting lib issue, and will be fixed next update on their end, we can't really do anything about it. Sorry for the inconvenience.

This will be fixed next update over there.

https://github.com/Fabricators-of-Create/Porting-Lib/issues/94

**Comment by ChrysanthCow** [comment]
For now, I'd suggest going into your Mod Menu config and setting `show_libraries` to false.

**Comment by ChrysanthCow** [comment]
Fixed in latest version.
