### ISSUE TITLE
Unable to craft roast chicken

### ISSUE THREAD

**Issue by popums** [MehVahdJukaar/FarmersDelightRefabricated#131]
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.7

### Fabric Loader version

Whichever Curseforge uses

### Fabric API version

0.110.0+1.21.1

### Description

Recipe for roast chicken is not working. I tried the old recipe that adds an egg, also doesn't work.
![image2](https://github.com/user-attachments/assets/35e83ad1-48e9-42c2-97cb-aee7b190d7bd)
![image1](https://github.com/user-attachments/assets/e140a8fc-b2b6-4f0b-bf42-26e2edb4491c)

### Steps to reproduce

Attempt to craft roast chicken

### Mod list

AppleSkin, Athena, Blur+, Carry On, Chipped, ChoiceTheorem's Overhauled Village, CIADA, Collective, Complementary Shaders (Reimagined and Unbound), Do a Barrel Roll, Double Doors, Fabric API, Iris Shaders, Just Enough Items (JEI), Just Zoom, Konkrete [Fabric], Lithium (Fabric/NeoForge), Lithostitched, ModernFix, Mousetweaks, Nature's Compass, Reese's Sodium Options, Resourceful Lib, Sodium, Sodium/Embeddium Dynamic Lights, Sodium/Embeddium Options API, Tom's Simple Storage Mod (Fabric), Xaero's Minimap, Xaero's World Map

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Tag issue, will be fixed in new version.
