### ISSUE TITLE
Bone Broth Recipe Does Not Work in Cooking Pot

### ISSUE THREAD

**Issue by haleyintech** [MehVahdJukaar/FarmersDelightRefabricated#132]
### Minecraft version

1.21.1

### Farmer's Delight version

2.2.7

### Fabric Loader version

i literally cannot find this.....

### Fabric API version

0.110.0+1.21.1

### Description

Bone Broth Recipe does not produce bone broth in Cooking Pot - does nothing despite recipe being in JEI.

![image](https://github.com/user-attachments/assets/fa256ccd-2d1e-4eac-aa97-698d646d6bb3)

![image](https://github.com/user-attachments/assets/fae4dd99-4fac-47c9-9490-79ed84f157fd)
^^ Tried all of these for the bone broth and nothing produces bone broth.

### Steps to reproduce

Place mushroom in Cooking Pot, or any other option in the bone broth recipe, and wait for recipe to be produced. Nothing happens.

### Mod list

All mods in this mod-pack, version 10:

https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric-mmc3

### Logs

![image](https://github.com/user-attachments/assets/6ba62e8a-0e39-4064-9d22-7189cab0f143)
The console doesn't produce any logs unfortunately related to this, or I couldnt isolate them, but here is an in game example

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
This is an issue with tags. This should be fixed as of the next update.
