### ISSUE TITLE
Wheat dough from eggs recipe only requires wheat

### ISSUE THREAD

**Issue by DeveloperGY** [MehVahdJukaar/FarmersDelightRefabricated#134]
### Minecraft version

1.21.1

### Farmer's Delight version

1.21.1-2.2.7+refabricated

### Fabric Loader version

0.16.9

### Fabric API version

0.110.0+1.21.1

### Description

The recipe for making wheat dough (labeled wheat_dough_from_eggs) only requires wheat and no eggs

### Mod list

- Architectury
- Better Ping Display
- Bobby
- Bookshelf
- Chunky
- Cloth Config v15
- Concurrent Chunk Management Engine
- Controlling
- Dark Loading Screen
- EnchantmentDescriptions
- FTB Library
- FTB Ultimine
- Fabric API
- Fabric Language Kotlin
- Farmer's Delight
- Fast IP Ping
- Highlighter
- Iceberg
- ImmediatelyFast
- Iris
- Jade
- Just Enough Items
- Just Zoom
- Keybind Fix Plus
- Konkrete
- Lithium
- M\.R\.U
- Mod Menu
- Model Gap Fix
- Noisium
- Ocean's Delight
- Placeholder API
- PrickleMC
- Reese's Sodium Options
- Remove Reloading Screen
- Searchables
- Sodium
- Sodium Extra
- Sound Physics Remastered
- Sounds
- Status Effect Bars
- Xaero's Minimap
- Xaero's World Map
- Yeetus Experimentus
- e4mc

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by DeveloperGY** [comment]
![image](https://github.com/user-attachments/assets/9659efeb-6941-4508-80dc-e9953786d1db)
heres a screenshot from jei

**Comment by ChrysanthCow** [comment]
Tags are bugged on the current version, will be fixed in the upcoming version today.
