### ISSUE TITLE
No support for Brewin' and Chewin' Farmer's Delight addon

### ISSUE THREAD

**Issue by TheTrueYak** [MehVahdJukaar/FarmersDelightRefabricated#16]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.12

### Fabric Loader version

0.15.6

### Fabric API version

0.92.0+1.20.1

### Description

Farmer's Delight Refabricated crashes on launch with Brewin' and Chewin' and I was wondering if compatibility would be added.

### Mod list

- brewinandchewin fabric-2.3.1+1.20.1
- fabric-api 0.92.0+1.20.1
- farmersdelight 1.20.1-2.0.12

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Hi, so Brewin' n Chewin' is one of the more complicated addons. So unfortunately, I doubt we can.

**Comment by ChrysanthCow** [comment]
The developer for BnC Fabric is likely working on it from what I've last heard though, so there'll be some waiting involved.

**Comment by NolanHewitt** [comment]
Farmers Respite by the same mod creator also causes issues. Is this also something that has to be fixed by that mod dev?

**Comment by ChromaPIE** [comment]
Also Cultural Delight. but i'm sure if they truly started working on the compat they'll do it for all their mods.

**Comment by ChrysanthCow** [comment]
> Farmers Respite by the same mod creator also causes issues. Is this also something that has to be fixed by that mod dev?

Yeah, Jukaar tried this one and it was too complicated.

**Comment by ChromaPIE** [comment]
BnC 3.0.0 now supports refabricated

**Comment by NolanHewitt** [comment]
Sadly the new version of BnC gets flagged as a virus by windows defender so I'm unable to use it.

**Comment by Poopooracoocoo** [comment]
why not just remove it from the quarantine

**Comment by ChrysanthCow** [comment]
> Sadly the new version of BnC gets flagged as a virus by windows defender so I'm unable to use it.

Windows Defender has been getting a lot of false positives relating to mods.

**Comment by ChrysanthCow** [comment]
Closed because BnC Fabric now has special versions for Refabricated
