### ISSUE TITLE
CTOV Farmers Delight Compatibility pack compat

### ISSUE THREAD

**Issue by NolanHewitt** [MehVahdJukaar/FarmersDelightRefabricated#19]
### Minecraft version

1.20.1

### Farmer's Delight version

newest

### Fabric Loader version

newest

### Fabric API version

newest

### Description

Will this datapack require an update from its creator to work with this version of FD, or could it be possible for a compatibility layer be added to this mod?

[The datapack in question](https://www.curseforge.com/minecraft/texture-packs/ctov-farmer-delight-compat)

### Mod list

.

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChoiceTheorem** [comment]
No, you don't need any compat datapack. But the compat with this mod is coming.

**Comment by NolanHewitt** [comment]
Actually, it looks like Chefs Delight and this CTOV village add-on datapack already work with this new version of farmers delight! Not sure if there are any bugs or compatibility things that need to be fixed but so far it looks like it works just fine.
