### ISSUE TITLE
Game Crashes When Starting on 1.20.1 Fabric

### ISSUE THREAD

**Issue by Rhett008** [MehVahdJukaar/FarmersDelightRefabricated#23]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.13

### Fabric Loader version

0.15.6

### Fabric API version

0.92.0+1.20.1

### Description

When attempting to start the game with minimal mods, the game crashes with exit code -1 after clicking Play from the Minecraft launcher.
<img width="420" alt="Screenshot 2024-04-07 174159" src="https://github.com/MehVahdJukaar/FarmersDelight/assets/160710805/95bd9936-091a-463d-ae3e-b096753c85a0">

### Steps to reproduce

Attempt to launch the game with specified mods and fabric loader version. After some time, receive the exit code and crash report.

### Mod list

Cloth-config
Fabric API
Farmer's Delight Refabricated
Ferrite Core
Indium
Iris
Just Enough Items
Sodium
Ube's Delight

### Logs

https://mclo.gs/fAOh7Bv

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by kingstairs** [comment]
Try disabling Ube's Delight - it might not be compatible with Refabricated (yet)? I believe some Farmer's Delight fabric mods are not 100% compatible with Refabricated.

**Comment by Rhett008** [comment]
> Try disabling Ube's Delight - it might not be compatible with Refabricated (yet)? I believe some Farmer's Delight fabric mods are not 100% compatible with Refabricated.

Yep, just tried without Ube's Delight and still receive the same crash result. Ube's released a compatibility patch anyway which is what I am trying to use (v 1.5.3).

+ issue persists with new FD refab patch (2.0.14)

**Comment by DoctorSclero** [comment]
+1

**Comment by ChrysanthCow** [comment]
For some reason, Porting Lib is not being loaded from Farmer's Delight Refabricated.

**Comment by ChrysanthCow** [comment]
# The fix is to update Fabric Loader
0.15.6 is somehow broken.
