### ISSUE TITLE
Game freezes on entering newly created world

### ISSUE THREAD

**Issue by ChromaPIE** [MehVahdJukaar/FarmersDelightRefabricated#25]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.16

### Fabric Loader version

0.15.9

### Fabric API version

0.92.0

### Description

See reproduction steps.

### Steps to reproduce

1. Enter the game, create a new world
2. Error screen. Saying there are errors on the resources between the server and client, then returns me to the server selection screen, even though I'm trying to create a singleplayer world
3. Open the saves folder and I see the world actually got created, but it's not shown in the world list
4. Retry creating another new world
5. Game freezes while loading, printing the crash report to the log

### Mod list

https://mclo.gs/tEdY5Sk

### Logs

Crash report: https://mclo.gs/prrJ2h9

The problem only happened when I updated Tectonic, More Delight, Every Compat and Farmer's Delight Refabricated this morning, and though I can't see the crash log any related to FD-R, it's the only mod of the four that has Porting Lib, which was mentioned by the log, embedded. I'm no pro so I can only report it here.

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Hi, I am unable to reproduce with just the mods you've mentioned. I'm unsure what could be going on...

**Comment by ChrysanthCow** [comment]
I'd suggest trying to either update Farmer's Delight Refabricated to 2.1.0 when it releases, or update PortingLib.

**Comment by ChromaPIE** [comment]
Crash fixed using 2.1.0. closing the issue
