### ISSUE TITLE
[Feature Request] Fabric Seasons: Delight Compat Support

### ISSUE THREAD

**Issue by 3ncanis** [MehVahdJukaar/FarmersDelightRefabricated#26]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.16

### Fabric Loader version

0.15.9

### Fabric API version

0.92.1

### Description

https://modrinth.com/mod/fabric-seasons-delight-compat

It seems like it already half-works, as in a few of the seeds show the correct tooltip saying they grow faster in X season, but some don't.

![Base Profile Screenshot 2024 04 09 - 20 38 29 83](https://github.com/MehVahdJukaar/FarmersDelight/assets/133993378/f1e71f66-7db6-42dd-98e3-5bca16d7b335)
![Base Profile Screenshot 2024 04 09 - 20 38 32 49](https://github.com/MehVahdJukaar/FarmersDelight/assets/133993378/d902718f-9808-4ed0-997b-8df22b35754f)

### Steps to reproduce

Install Farmers Delight Refabricated
Install Fabric Seasons + Delight Compat

### Mod list

Farmer's Delight Refabricated
Fabric Seasons
Fabric Seasons: Delight Compat
Reqs

### Logs

N/A

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Hello, this will require them to update their mod.

Simply because they mixin to Farmer's Delight Fabric classes.
