### ISSUE TITLE
Barbecue on a Stick recipe uses wrong tag

### ISSUE THREAD

**Issue by No1RatMovieFan** [MehVahdJukaar/FarmersDelightRefabricated#27]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.16

### Fabric Loader version

0.15.9

### Fabric API version

0.92.1+1.20.1

### Description

The recipe for Barbecue on a Stick uses `c:foods/cooked_meats/cooked_fishes` instead of `c:foods/cooked_fishes` like the other recipes, preventing Barbecue on a Stick from being crafted with fish

### Mod list

- Fabric API
- Farmer's Delight Refabricated

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
fixed
