### ISSUE TITLE
Will not load world, speaks of incompatibility with resource pack/data pack

### ISSUE THREAD

**Issue by Voidmaster01** [MehVahdJukaar/FarmersDelightRefabricated#30]
### Minecraft version

1.20.1

### Farmer's Delight version

latest

### Fabric Loader version

0.15.9

### Fabric API version

0.92.1

### Description

when I try to load a world it shows me a screen telling me it cannot load due to resource pack failure, when i "run in safe mode" the game crashes showing me this log

### Mod list

Mod List comes from Landscapes Reimagined Genesis, also located in crash report below

### Logs

https://mclo.gs/2cPieDt

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Hello, this is an issue with Slice and Dice, SnD does not support Refabricated at this given moment. A link to the relevant issue is here.
https://github.com/PssbleTrngle/SliceAndDice/issues/140
