### ISSUE TITLE
Many tags are missing or renamed causing issues with recipies

### ISSUE THREAD

**Issue by NolanHewitt** [MehVahdJukaar/FarmersDelightRefabricated#31]
### Minecraft version

1.20.1

### Farmer's Delight version

newest

### Fabric Loader version

newest

### Fabric API version

newest

### Description

Tags for cooked chicken, cooked fishes, milk, and cooked mutton seem to be missing or renamed from some items causing many recipes to not work. For example, some recipes called for c:milk but it looks like the tag is now milks?

### Mod list

.

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by NolanHewitt** [comment]
Looking at the tags for the old port of farmers delight, it does look like many of the old tags are missing in the new version. Copying all the C tags from the old port into a datapack fixes these recipes. Perhaps these tags could be carried over for compatibility purposes? Many mods updated for refabricated but the recipes stayed the same so don't work without making a datapack like this.

**Comment by ChrysanthCow** [comment]
I'll see if I can add some backwards compat in this regard, because yeah, we've been working off the new common tags PR for our tag format, for an easier time updating past 1.20,1, but this isn't ideal, I'll see what I can do.

**Comment by ChrysanthCow** [comment]
Hi, I have been implementing some tags in a backwards compat way.

You can see the changes here: 89909ad.
