### ISSUE TITLE
automation of cutting only works for one item type

### ISSUE THREAD

**Issue by 800020h** [MehVahdJukaar/FarmersDelightRefabricated#33]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1-2.0.17+refabricated

### Fabric Loader version

0.15.7

### Fabric API version

0.92.1+1.20.1

### Description

when automating cutting hoppers and similar will only insert 1 item type unless you break and replace the board

### Steps to reproduce

1. set up a board with a hopper for input
2. put `example:cutting_input_one` in the hopper
3. cut until input runs out
4. put `example:cutting_input_two` in the hopper
5. observe it doesn't get put in the board
6. break and replace board
7. observe again

### Mod list

https://modrinth.com/modpack/spectrum-public-server-pack/version/2.0.0
scroll down to the dependencies part

### Logs

not logged afaik

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
So, items with a count of 0 do not automatically get converted to empty, which was causing this.
