### ISSUE TITLE
"Could not find" errors when depending on the mod using Gradle

### ISSUE THREAD

**Issue by FlooferLand** [MehVahdJukaar/FarmersDelightRefabricated#34]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1-2.0.17+refabricated

### Fabric Loader version

0.15.10

### Fabric API version

0.92.1+1.20.1

### Description

I get a wall of missing maven repos any time I try to depend on this mod. I've tried cleaning it, tried researching it, and the only lead I could find is that some random dude got these errors because of a problem with jitpack, which seems completely irrelevant here. The repositories seem fine, nothing moved to a new url.

I've followed the [Depending on Farmer's Delight Refabricated](https://github.com/MehVahdJukaar/FarmersDelight?tab=readme-ov-file#depending-on-farmers-delight-refabricated) section exactly as its written. I've also tried using Modrinth's maven repo instead of the Green House Team one, which just made me get a "unfixable conflict" error.

My `build.gradle` looks like [this](https://pastebin.com/1QsfLEf4)
`gradle.properties` contains `farmers_delight_version=1.20.1-2.0.17+refabricated`

It seems like a problem regarding `PortingLib`, but again, not sure what to do. Repo seems fine.

### Steps to reproduce

Followed the [Depending on Farmer's Delight Refabricated](https://github.com/MehVahdJukaar/FarmersDelight?tab=readme-ov-file#depending-on-farmers-delight-refabricated) section for my project. (I know, not very reproducible since its closed-source for now)

### Mod list

n/a

### Logs

https://pastebin.com/pnikbz5g

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by FlooferLand** [comment]
A user called Abbie on the Discord just helped me fix this.
- https://mvn.devos.one/releases/ should be replaced with https://mvn.devos.one/snapshots/ in the `build.gradle`
- Jitpack is required for PortingLib (FabricASM):
  ```gradle
  maven {
      url = "https://jitpack.io/"
      content {
          includeGroup "com.github.Chocohead"
      }
  }
  ```
- There are mapping issues with Yarn and I need to rename like 10 methods.

The README should probably be updated to feature some of this stuff

**Comment by ShiftySpace** [comment]
Thank you so much for posting the update. Helped me out a ton. I knew it had something to do with jitpack.io so it got me the rest of the way there

**Comment by FlooferLand** [comment]
> Thank you so much for posting the update. Helped me out a ton. I knew it had something to do with jitpack.io so it got me the rest of the way there

No worries xD
Even with all the help I didn't end up getting it working myself, thought i did.
I've just kinda given up using Farmers Delight for my mod, building all the food stuff by myself instead.
The several Fabric versions and forks of Farmer's Delight have been the one reason I wasn't able to update my mod to 1.20.4 for the past like 8 months so I'm pretty glad to get rid of it ngl xD

closing the thread since its turning into a chat eughhhh
