### ISSUE TITLE
Wrong fluid amount in Fabric version (I think)

### ISSUE THREAD

**Issue by MrRedstoneToGo** [MehVahdJukaar/FarmersDelightRefabricated#37]
https://github.com/MehVahdJukaar/FarmersDelight/blob/fdbbb7acfbb5013a562249df6a39fbc26b75efc4/src/main/resources/data/farmersdelight/recipes/integration/create/mixing/pie_crust_from_mixing.json#L21-24

You only need 3mB of milk for the recipe. I think that should be 250mB. Fabric, unlike Forge, does not calculate in liters, but in some other unit, I don't know the name right now. 81,000 is a bucket (81 = 1mB). So you don't need 250 as the amount here, but 250 * 81 = 20,250.

**Comment by BugInYourCode01** [comment]
Also applies to chocolate pie filling

**Comment by ChrysanthCow** [comment]
Thank you for the rundown of this issue.

**Comment by ChrysanthCow** [comment]
They use droplets as a fyi, but this should be fixed as of next version.

**Comment by BugInYourCode01** [comment]
I use the Modrinth launcher and the live logs there are very informative.
