### ISSUE TITLE
cooking pot automation very broken

### ISSUE THREAD

**Issue by 800020h** [MehVahdJukaar/FarmersDelightRefabricated#39]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1-2.1.0

### Fabric Loader version

0.15.7

### Fabric API version

0.92.1+1.20.1

### Description

hoppers can extract from all slots of the cooking pot (including the serving queue without a container)
they should only be able to extract from the output

### Steps to reproduce

- put pot on hopper
- add items
- observe
- remove hopper
- add items, but not container
- make cooking happen
- replace hopper
- observe free plate spawner

### Mod list

lots of them but none relevant afaik

### Logs

not logged

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by 800020h** [comment]
also affected 1.20.1-2.0.17 but I found it too late to confirm and report it before the update

**Comment by ChrysanthCow** [comment]
I'll look into this when I can.

**Comment by ChrysanthCow** [comment]
This has been a tricky one, due to my absolute unfamiliarity with Fabric's Transfer API, but a fix has been released in 2.1.1
