### ISSUE TITLE
Having Some visual issues with crop textures

### ISSUE THREAD

**Issue by Delfonso** [MehVahdJukaar/FarmersDelightRefabricated#4]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.1

### Forge version

Fabric

### Description

![2024-03-27_09 09 28](https://github.com/MehVahdJukaar/FarmersDelight/assets/123846468/8810c564-075a-4e30-8468-e9b195c3c30b)

### Mod list

alternate-current: Alternate Current 1.7.0
		ambientenvironment: Ambient Environment 11.0.0.1
		amendments: Amendments 1.20-1.1.12
			mixinsquared: MixinSquared 0.1.1
		armorful: Armorful 2.0.2+1.20
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		audaki_cart_engine: Audaki Cart Engine 2.0.6
		autoslabs: AutoSlabs 1.1.3
			advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0
			statement: Statement 4.2.8+1.14.4-1.20.1
				kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
				statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		beansbackpacks: BeansBackpacks 0.21-v2
		bedoverhaul: BedOverhaul 1.0.2
		betterarcheology: Better Archeology 1.1.6-1.20.1
		betterbeds: Better Beds 1.3.0
		betterclouds: Better Clouds 1.3.16+1.20.1
		bettercombat: Better Combat 1.8.4+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		bettermounthud: Better Mount HUD 1.2.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthirdperson: Better Third Person 1.9.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		bundlescroll: Bundle Scroll 1.1.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		charmonium: Charmonium 6.0.7
			charmony: Charmony 6.12.0
			charmony_api: Charmony API 6.7.0
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		clean_tooltips: Clean Tooltips 1.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.40
		companion: Companion 5.1.0
		copperandtuffbackport: CopperandTuffBackport 1.2
		copperhopper: Copper Hopper 0.5.1+1.20.1
		cullleaves: Cull Leaves 3.2.0
		debugify: Debugify 1.20.1+2.0
		dismountentity: Dismount Entity 3.2
		dynamic_fps: Dynamic FPS 3.4.2
		dynamiclights: Dynamic Lights 1.7.1+mod
		eatinganimationid: Eating Animation 1.20+1.9.61
		emi: EMI 1.1.4+1.20.1+fabric
		endrem: End Remastered 5.2.4
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		exordium: Exordium 1.2.1-mc1.20.1
		explorify: Explorify v1.3.0-mc1.20
		exposure: Exposure 1.4.1
		extra-mod-integrations: Extra Mod Integrations 0.4.3+1.20.1
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		fallingleaves: Falling Leaves 1.15.5
		farmersdelight: Farmer's Delight 1.20-2.0.1
			porting_lib_accessors: Porting Lib Accessors 2.1.1192+1.20.1
			porting_lib_base: Porting Lib Base 2.1.1192+1.20.1
				porting_lib_entity: Porting Lib Entity 2.1.1192+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.1.1192+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1192+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.1.1192+1.20.1
				porting_lib_utility: Porting Lib Utility 2.1.1192+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.1.1192+1.20.1
			porting_lib_config: Porting Lib Config 2.1.1192+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.1.1192+1.20.1
				porting_lib_asm: Porting Lib ASM 2.1.1192+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.1.1192+1.20.1
				porting_lib_common: Porting Lib Common 2.1.1192+1.20.1
				porting_lib_core: Porting Lib Core 2.1.1192+1.20.1
				reach-entity-attributes: Reach Entity Attributes 2.4.0
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1192+1.20.1
			porting_lib_loot: Porting Lib Loot 2.1.1192+1.20.1
			porting_lib_networking: Porting Lib Networking 2.1.1192+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.1.1192+1.20.1
			porting_lib_registries: Porting Lib Registries 2.1.1192+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1192+1.20.1
		fastpaintings: Fast Paintings 1.20-1.2.5
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
			org_javassist_javassist: javassist 3.29.2-GA
		frostiful: Frostiful 1.0.7
			mm: Manningham Mills 2.3
		frycmobvariants: Mob Variants 4.4.1+1.20
		galosphere: Galosphere 1.20.1-1.4.1
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		geophilic: Geophilic v2.2.0-mc1.20u1.20.2
		guarding: Guarding 2.4.0
			scribe: Scribe 1.20.1-0.5.0-alpha
		guicompass: GUI Compass 4.4
		hearths: Hearths v1.0.0-mc1.20u1.20.1
		horsebuff: HorseBuff 2.1.2
		indium: Indium 1.0.30+mc1.20.4
		java: Java HotSpot(TM) 64-Bit Server VM 17
		leavesbegone: Leaves Be Gone 8.0.0
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.1.5
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		map_atlases: Map Atlases 2.6.0
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.15
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.11.9
		moremobvariants: More Mob Variants 1.2.2
		mr_edf_remastered: Ender Dragon Fight Remastered 4.3
		mr_tool_trims: Tool Trims 2.0.2+1.20
		mru: Mineblock's Repeated Utilities 0.4.0+1.20
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nerb: Not Enough Recipe Book 0.3
		notenoughanimations: NotEnoughAnimations 1.7.1
		notes: Notes 1.20.1-2.1.0-fabric
		nvidium: Nvidium 0.2.6-beta
		nyfsspiders: Nyf's Spiders 2.1.1
		paperdoll: Paper Doll 8.0.0
		particle_core: Particle Core 0.1.2+1.20
			conditional-mixin: conditional mixin 0.5.1
			fzzy_config: Fzzy Config 0.1.3+1.20.1
		phantasm: End's Phantasm 0.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		puzzleslib: Puzzles Lib 8.1.18
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		revitalized_outposts: Revitalized Outposts 1.0.0
		reworked_sleep_to_night: Reworked: Sleep To Night 1.1.0
		scorchful: Scorchful 0.3
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
		simplefog: Simple Fog Control 1.4.0
		snowundertrees: Snow Under Trees 2.2.0+1.20.1
		sodium: Sodium 0.5.8+mc1.20.1
		sounds: Sounds 0.6.0+1.20.1
		spyglass_astronomy: Spyglass Astronomy 1.0.10-mc1.20.0-1
		structory: Structory 1.3.4
		supplementaries: Supplementaries 1.20-2.8.8
		thermoo: Thermoo 2.2
		timecontrol: TimeControl 1.6.0
		tinkerers_smithing: Tinkerer's Smithing 2.6.7+1.20
			folk_sisby_kaleido-config: kaleido-config 0.2.0+1.2.0-beta.5
		tooltipfix: ToolTip Fix 1.1.1-1.20
		vanillazoom: Vanilla Zoom 2.3
		villagerfix: Villager Trade Fix 1.0.4
		villagernames: Villager Names 7.3
		villagesandpillages: Villages&Pillages 1.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.4

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
oh noe
