### ISSUE TITLE
Mod incompatible with Optifine + Optifabric

### ISSUE THREAD

**Issue by drawonmyskin** [MehVahdJukaar/FarmersDelightRefabricated#43]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.1

### Fabric Loader version

0.15.10

### Fabric API version

0.92.1+1.20.1

### Description

I get error 1 when I try to load my fabric launcher with both Farmer's Delight Refabricated and Optifine and Optifabric at the same time. I have an entire modpack, none of the others have compatibility with Optifine/Optifabric nor FD Refabricated, just the two of them with each other.
Optifine Version: 1.20.1 HD U I6
Optifabric Version: 1.14.3

### Steps to reproduce

1. Put optifabric, optifine, FDR, and Fabric API in the mods folder
2. Launch the game with these mods in it
3. Encounter Error 1

### Mod list

Fabric
Fabric API
Optifine
Optifabric
Farmer's Delight Refabricated

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
Dont use Optifine. It breaks countless mods and its performance increase is risible when compared to actual performance mods like embeddium sodium, modernfix and many others

**Comment by ChrysanthCow** [comment]
Not planned because Optifine is closed source, and messes with too much that we don't know of.
