### ISSUE TITLE
unable to plant stem plants on rich soil farmland (pumpkin, melon)

### ISSUE THREAD

**Issue by 800020h** [MehVahdJukaar/FarmersDelightRefabricated#44]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1-2.1.1

### Fabric Loader version

0.15.10

### Fabric API version

0.92.1+1.20.1

### Description

you can't plant stem plants on rich soil farmland

ones planted while using Farmer's Delight [Fabric] broke when they got a block update

### Steps to reproduce

- try planting pumpkins or melons on rich soil farmland
- observe

### Mod list

lots of them

### Logs

not logged

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by 40411** [comment]
I have encountered the same problem on version 1.20.1-2.1.1

**Comment by ChrysanthCow** [comment]
I need to rewrite the code for Rich Soil Farmland compatibility, it's really not great for modded compat atm.

**Comment by MehVahdJukaar** [comment]
this should be something that porting lib should have done... fixed
