### ISSUE TITLE
Add corn's delight to Addons_And_Integrations.md

### ISSUE THREAD

**Issue by ShiftySpace** [MehVahdJukaar/FarmersDelightRefabricated#48]
I created a corn's delight refabricated version. https://github.com/ShiftySpace/CornDelight-refabricated

sent a pull request with the main project but haven't heard from the owner. But you can update the sheet saying there is a compatible version. I can release a compiled version of the mod so it is easier for people to download if you'd like

**Comment by ChrysanthCow** [comment]
Solved by #53
