### ISSUE TITLE
[SUGGESTION] Configuration menu or files

### ISSUE THREAD

**Issue by MMG778** [MehVahdJukaar/FarmersDelightRefabricated#49]
### Minecraft version

1.20.1

### Farmer's Delight version

#

### Fabric Loader version

#

### Fabric API version

#

### Description

Please add a whole feature configuration menu or files so that we can configure it because I would like to use Farmer's Delight Refabricated with Croptopia and there are certain things I like better in Croptopia and in Farmer's Delight Refabricated.

### Mod list

Croptopia
Croptopia Additions
All compatible Farmer's Delight Refabricated add-ons

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
mod already has its own config. doesnt that work?
