### ISSUE TITLE
Gradle fails to import project depending on Farmer's Delight Refabricated when using Yarn mappings: "unfixable conflicts"

### ISSUE THREAD

**Issue by unilock** [MehVahdJukaar/FarmersDelightRefabricated#5]
The error shown in IntelliJ:

```
> Configure project :
Fabric Loom: 1.5.8
:remapping 1 mods from modImplementation (java-api)
Mapping target name conflicts detected:
  METHODs vectorwing/farmersdelight/client/renderer/SkilletItemRenderer/[render, net/minecraft/class_756/method_3166](Lnet/minecraft/class_1799;Lnet/minecraft/class_811;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;II)V -> render
There were unfixable conflicts.
```

`method_3166` maps to `renderByItem`.

Maybe a JAR mapped to Intermediary could be provided?

**Comment by MehVahdJukaar** [comment]
you should be using official mojang mappings. Ill rename that methdod since i can juse make it not subclass that class on fabric. For other occurrences it would have not been that lucky

**Comment by ChrysanthCow** [comment]
I'll be uploading files to my maven, so be on the lookout for then.

**Comment by ChrysanthCow** [comment]
Please try with the new maven, if not, wait on the fix mentioned above.

**Comment by unilock** [comment]
The latest version on the maven (v1.20.1-2.0.10) is working great with Yarn, thanks!

Note that it's also necessary to add [Curse Maven](https://cursemaven.com/) to the `repositories { ... }` block in `build.gradle`, as Farmer's Delight Refabricated depends on [Fright's Delight](https://www.curseforge.com/minecraft/mc-mods/frights-delight) for some reason...?

**Comment by ChrysanthCow** [comment]
> The latest version on the maven (v1.20.1-2.0.10) is working great with Yarn, thanks!
> 
> Note that it's also necessary to add [Curse Maven](https://cursemaven.com/) to the `repositories { ... }` block in `build.gradle`, as Farmer's Delight Refabricated depends on [Fright's Delight](https://www.curseforge.com/minecraft/mc-mods/frights-delight) for some reason...?

I'll comment out that line next update. That was a mistake.
