### ISSUE TITLE
Lucky Block Incompatibility past 2.0.12 Refabricated

### ISSUE THREAD

**Issue by HeliosAzuria** [MehVahdJukaar/FarmersDelightRefabricated#52]
### Minecraft version

1.20.1

### Farmer's Delight version

All That I've tested past 0.12 but 2.1.1 specifically

### Fabric Loader version

Quilt 0.25.0

### Fabric API version

0.91 (though its qfapi)

### Description

It's more than anything funny, it's an entrypoint opening crash with lucky blocks of all things.

![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/173515905/b782766b-27af-48c8-b13d-5880f952219f)

### Steps to reproduce

Literally just booting the game with lucky blocks

### Mod list

[most recent crash.txt](https://github.com/user-attachments/files/15934581/most.recent.crash.txt)
sorry if this isn't what you meant

### Logs

[latest.log](https://github.com/user-attachments/files/15934583/latest.log)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
looks to me thisissue comes directly from that mod or maybe quilt. This port was made for fabric

**Comment by ChrysanthCow** [comment]
This definitely doesn't look to be on our end. Nothing really points this to us.
