### ISSUE TITLE
Peperonata Recipe dind't work

### ISSUE THREAD

**Issue by ericklfr** [MehVahdJukaar/FarmersDelightRefabricated#57]
### Minecraft version

1.2

### Farmer's Delight version

latest

### Fabric Loader version

0.15.11

### Fabric API version

0.15.11+1.2

### Description

When I try cook the Peperonata, nothing happing, even If I put all the necessary ingredients:

![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/25674791/8762ce8c-c417-4ec4-9998-473e2cb9417f)
![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/25674791/217cc657-cbcb-4b1c-bf72-a4744ea2a962)

### Steps to reproduce

Put the peperonata ingredients and try to cook

### Mod list

Using modpack betterCraft

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
while I approve this recipe, this is NOT a recipe added by farmers delight refabricared and hence not our issue. Most ithers there arent from FDRF either
