### ISSUE TITLE
Rice Panicle Not Dropping from Mature Rice Crops.

### ISSUE THREAD

**Issue by Coddrin** [MehVahdJukaar/FarmersDelightRefabricated#58]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.1

### Fabric Loader version

0.15.11

### Fabric API version

0.92.2+1.20.1

### Description

Cannot get the rice panicle from mature rice crops, tried shears, knife, silk touch and breaking the bottom half of the mature crop to see of it would give the panicle that way (nope).

### Steps to reproduce

Grow Rice to mature crop then try to harvest.

### Mod list

Amplified Nether
AppleSkin
Architectury API
BCLib
Better Compressed Blocks
BetterEnd
Bewitchment
Brewin' And Chewin' [Fabric]
Cardinal Components API
Charm of Undying
Chunk Loaders
Cloth Config API
Controlling 
Cosmetic Armor
Crate Delight - Farmer's Delight
Create Cobblestone
Create Enchantment Industry Fabric
Create Fabric
Create Slice & Dice
Create: Steam 'n' Rails
Delightful Creators [Fabric]
Elytra Slot
Embeddium
Enchanting Infuser
Essential Mod
Fabric API
Fabric Language Kotlin
Farmer's Delight Expansion
Farmer's Delight Refabricated
Farmer's Knives [Fabric]
FerriteCore
First-person Model
Forge Config API Port
Fright's Delight
Geckolib
Gravestones
Jade :mag:
Just Enough Farmer's Recipes
Just Enough Items
Just Hammers
LazyDFU
Mod Menu
ModernFix
More Delight - Farmer's Delight
Mouse Tweaks
Mythic Mounts
Nature's Compass
Nethers Delight Refabricated
Origins
Origins: Classes
Patchouli
Pehkui
PneumonoCore
Puzzles Lib
Respite Creators [Fabric]
Searchables
Storage Delight - Farmer's Delight
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
Terralith
Traveler's Backpack
Trinkets
Ube's Delight
Xaero's Minimap
Xaero's World Map
YUNG's API
YUNG's Better Desert Temples
YUNG's Better Dungeons
YUNG's Better End Island
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YUNG's Better Strongholds
YUNG's Better Witch Huts
YUNG's Menu Tweaks

### Logs

[23:11:27] [main/INFO]:
 Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[23:11:27] [ForkJoinPool-1-worker-2/WARN]:
 Mod frightsdelight uses the version fabric-1.20.1-1.0.4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[23:11:28] [ForkJoinPool-1-worker-3/WARN]:
 Mod travelersbackpack uses the version fabric-1.20.1-9.1.15 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-api-base 0.4.31+1802ada577
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=9'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=12'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=13'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=10'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=11'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=0'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=14'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=15'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=3'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=4'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=1'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=2'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=7'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=8'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=5'
[23:12:21] [Worker-ResourceReload-1/WARN]:
 Exception loading blockstate definition: 'delightfulcreators:blockstates/cooked_rice_block.json' missing model for variant: 'delightfulcreators:cooked_rice_block#level=6'
[23:12:46] [Render thread/WARN]:
 Unknown recipe category: brewinandchewin:fermenting/brewinandchewin:fermenting/rice_wine
[23:45:32] [Render thread/WARN]:
 Unknown recipe category: brewinandchewin:fermenting/brewinandchewin:fermenting/rice_wine
 (these were the only things i could find even revolving around rice)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
are you sure they are fully mature? the second to last stage can look mature when it isnt

**Comment by Bugord** [comment]
same for me

**Comment by MehVahdJukaar** [comment]
same asnwer then

**Comment by Bugord** [comment]
My bad, I've checked each mod, the problem was in farmers-delight-expansion (error in loot table, dev mixed up rice_panicle/rice_panicles)
