### ISSUE TITLE
Cant till rich soil

### ISSUE THREAD

**Issue by Delfonso** [MehVahdJukaar/FarmersDelightRefabricated#6]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.5

### Forge version

fabric

### Description

Cant till rich soil. Also if you get it from the creative inventory you cant place crops on it. 

### Mod list

fabric api
farmers delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
porting lib is failing us here 💀

**Comment by ChrysanthCow** [comment]
The latter part of this issue is likely related to:
https://github.com/Fabricators-of-Create/Porting-Lib/issues/21

But the first issue will be something I'll create for over there.

We'll probably sidestep this for now.

**Comment by ChrysanthCow** [comment]
I'll push out a fix for both of these issues as soon as I get home.

**Comment by ChrysanthCow** [comment]
Fixed in 2.0.7
