### ISSUE TITLE
Complications with No Tree Punching Mod

### ISSUE THREAD

**Issue by REDACTED6045** [MehVahdJukaar/FarmersDelightRefabricated#60]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.2

### Fabric Loader version

0.16.0

### Fabric API version

0.92.2

### Description

When I have installed Farmers Delight Refabricated, the "Plant Fiber"(No Tree Punching mod) does not drop from grass or tall grass at all.

### Mod list

https://modrinth.com/mod/no-tree-punching/version/POWV0EfQ

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
this mode uses porting lib loot modifiers, if they conflict with no tree punching then that mod likely has that conflict with porting lib, or removing loot from grass is an intentional feature of it

**Comment by ChrysanthCow** [comment]
Likely fixed by Porting Lib 2.3.8+1.20.1
