### ISSUE TITLE
Feature: fabric 1.20.4 ? 

### ISSUE THREAD

**Issue by nmwael** [MehVahdJukaar/FarmersDelightRefabricated#62]
Are there any intentions of adding support for fabric/minecraft 1.20.4?

**Comment by nmwael** [comment]
I have no idea if this is trivial or not.. Althoug if every api maker are following semver, it should be :)

**Comment by DuckDuckStudio** [comment]
I think should can support 1.20.4 when [Porting Lib](https://github.com/Fabricators-of-Create/Porting-Lib/) updated. :)
- https://github.com/MehVahdJukaar/FarmersDelight/issues/10#issue-2214448918

**Comment by MehVahdJukaar** [comment]
no plan to support such minor intermediate version

**Comment by nmwael** [comment]
> no plan to support such minor intermediate version

AFAIK mojang broke semver, and 1.20.4 is the last version supporting java 17. SO it might sound like an small intermediate version but it is not. Just for heads up..

**Comment by MehVahdJukaar** [comment]
You are right, while it's definitely intermediate it's not small. It's a snapshot version with major internal changes so major work would be needed to port to that. Besides we depend on porting lib and that too isn't for that version, rightfully so. 
Also most people play on 1.20.1 these days. Servers or not
