### ISSUE TITLE
Implement integration with "Mindful Eating - Fabric"

### ISSUE THREAD

**Issue by foxf4ce** [MehVahdJukaar/FarmersDelightRefabricated#63]
[Mindful Eating - Fabric](https://modrinth.com/mod/mindful-eating-fabric)

Mindful Eating's goal is to rework Minecraft's food system in order to incentivize a balanced diet in a non-intrusive way. Integrating this mod with Farmer's Delight would ideally follow camcam_burger's (aka camcamcamcamcam, the original Forge mod author) design philosiphy described in his [design log](https://github.com/camcamcamcamcam/mindful-eating/blob/main/designlog.txt) and his [video design log](https://www.youtube.com/watch?v=NN8Vgj4wrFw).

camcam_burger admitted himself that the prospect of balancing and adding support for other food focused mods was too large of a task and decided to add a feature which allows implementation using data.

**Comment by MehVahdJukaar** [comment]
hasnt somebody already made an addon that does this? that mod should be data driven so given how popular FD is somebody must have done that before
