### ISSUE TITLE
cooking pot only stores 16 servings

### ISSUE THREAD

**Issue by Wendro140** [MehVahdJukaar/FarmersDelightRefabricated#65]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.2

### Fabric Loader version

0.15.11

### Fabric API version

 0.92.2+1.20.1

### Description

![Minecraft_ 1 20 1 8_13_2024 8_36_13 PM](https://github.com/user-attachments/assets/6f9b5b51-bd91-45c5-9694-313d8199966c)

### Mod list

I first tried it with a a modpack, but after experimenting it doesn't even matter. I made a new instance with just Refabricated and the port by Zifiv (and fabric api obvi). after comparing and experimenting I found that only Refabricated has this issue, and that sucks bc I love the lil QOL things u guys added :(

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Mhm, this is a bug. You are correct.

I'll look into fixing it asap.

**Comment by ChrysanthCow** [comment]
![image](https://github.com/user-attachments/assets/808fe7f5-4cc9-486d-bf95-a1dba3130e9f)
Will be fixed in this upcoming version.
