### ISSUE TITLE
Cabinets do not extend barrels

### ISSUE THREAD

**Issue by vivvyinks** [MehVahdJukaar/FarmersDelightRefabricated#66]
Let me open by saying that yes this is somewhat esoteric, but the cabinets do not extend barrels, code-wise, and thus do not work on trains or contraptions in Create. I don't know how complicated or trivial this would be to fix, but it would be a useful change, as they're otherwise functionally identical to barrels (accessible from all sides, same amount of storage).

**Comment by Partonetrain** [comment]
Also prevents them from being used as Botania Corporea containers

**Comment by ChrysanthCow** [comment]
> Let me open by saying that yes this is somewhat esoteric, but the cabinets do not extend barrels, code-wise, and thus do not work on trains or contraptions in Create. I don't know how complicated or trivial this would be to fix, but it would be a useful change, as they're otherwise functionally identical to barrels (accessible from all sides, same amount of storage).

Please tell this to the official version of [Farmer's Delight](https://github.com/vectorwing/FarmersDelight/). We aren't going to change this unless the change happens on the other end.
