### ISSUE TITLE
Crash on startup with latest 1.21.1 mod version 

### ISSUE THREAD

**Issue by VaporeonScripts** [MehVahdJukaar/FarmersDelightRefabricated#68]
### Minecraft version

1.21.1

### Farmer's Delight version

2.1.3

### Fabric Loader version

0.16.2

### Fabric API version

latest

### Description

putting newly released version of farmers delight refabricated causes crash 

### Steps to reproduce

add the mod, start mc

### Mod list

[✔] [1.21] Legendary Item 24.07.19 (Fabric)
  [✔] [Fabric]CTOV-3.5.1
  [✔] a_good_place-1.21-1.2.4-fabric
  [✔] accessories_tclayer-3.10.0-beta.7+1.21
  [✔] accessories-fabric-1.0.0-beta.30+1.21
  [✔] accurate-block-placement-1.2.5
  [✔] additional-armoury-2.0.0+1.21
  [✔] additionalentityattributes-1.8.0+1.21
  [✔] additionallanterns-1.1.1-fabric-mc1.21
  [✔] AdditionalStructures-1.21-(v.5.0.0-fabric)
  [✔] adorabuild-structures-2.7.0-fabric-1.21.1
  [✔] advancednetherite-fabric-2.1.6-1.21.1
  [✔] advancementinforeloaded-0.4.2-1.21
  [✔] AdvancementPlaques-1.21-fabric-1.6.6
  [✔] adventurez-1.4.21
  [✔] allarrowsinfinityfix-1.7.2-fabric-mc1.21.1
  [✔] allow-portal-guis-1.1.1
  [✔] alloy-forgery-2.4.1+1.21
  [✔] AmbientSounds_FABRIC_v6.0.5_mc1.21
  [✔] anvilrestoration-1.21.1-2.3
  [✔] appleskin-fabric-mc1.21-3.0.5
  [✔] architectury-13.0.6-fabric
  [✔] artifacts-fabric-12.0.5
  [✔] athena-fabric-1.21-4.0.1
  [✔] automaticdoors-1.21.1-4.8
  [✔] azurelib-fabric-1.21.1-2.3.16
  [✔] BadOptimizations-2.1.4-1.21
  [✔] badpackets-fabric-0.8.1
  [✔] balm-fabric-1.21.1-21.0.18
  [✔] BasicNetherOres-fabric-1.21.1-10.1.0
  [✔] basicweapons-1.2.9+1.21
  [✔] bclib-21.0.13
  [✔] beautify-1.2.1+1.21
  [✔] beekeeperhut-fabric-mc1.21-2.0.1
  [✔] better_mcdonalds_mod-fabric-4.2.0+1.21
  [✔] better-enchanted-books-1.21-2.1.0
  [✔] better-end-21.0.9
  [✔] better-nether-21.0.11
  [✔] better-suggestions-1.21-1.2.7.1
  [✔] betterbeds-fabric-1.4.0
  [✔] betterendcities-betterend-1.21
  [✔] bettermounthud-1.2.4
  [✔] betterstats-3.13.2+fabric-1.21
  [✔] BetterThanBunnies-1.21-Fabric-1.4.0
  [✔] BetterThanLlamas-1.21-Fabric-1.3.0
  [✔] BetterThirdPerson-Fabric-1.21-1.9.0
  [✔] beyondenchant-1.5.0
  [✔] BiomesOPlenty-fabric-1.21-21.0.0.18
  [✔] blockus-2.9.2+1.21.1
  [✔] BOMD-1.10.1-1.21
  [✔] Boxlib-fabric-14.3.0
  [✔] brainierbees-1.6
  [✔] breadvariants-fabric-1.21-1.0.1
  [✔] breakfree-1.3.0
  [✔] brrp-fabric-1.0.4-1.21.1
  [✔] brutalbosses-fabric-1.21-7.1
  [✔] cardinal-components-api-6.1.1
  [✔] carryon-fabric-1.21.1-2.2.2.11
  [✔] caveoverhaul-fabric-1.21.1-1.3.3
  [✔] chat_heads-0.12.10-fabric-1.21
  [✔] chattools-1.21.1-v2.3.3
  [✔] chipped-fabric-1.21-4.0.0
  [✔] chunksending-fabric-1.21-2.8
  [✔] Chunky-1.4.16
  [✔] cinderscapes-5.0.1
  [✔] clean_tooltips-1.0-fabric-1.21
  [✔] CleanF3-0.4.6
  [✔] clickadv-fabric-1.21-3.8
  [✔] cloth-config-15.0.130-fabric
  [✔] Clumps-fabric-1.21.1-19.0.0.1
  [✔] coffdoublejump-2.0
  [✔] collective-1.21.1-7.84
  [✔] colorfulhearts-fabric-1.21.1-10.3.5
  [✔] combatplus-core-3.1.0+1.21
  [✔] connectiblechains-2.4.2+1.21.1
  [✔] CoordinatesDisplay-fabric-13.1.0
  [✔] coroutil-fabric-1.21.0-1.3.7
  [✔] CottageCraft-1.6.0-1.21.0
  [✔] CottageCraftAxolotls-1.3.0-1.21.0
  [✔] Craftify-1.21-1.16.0-fabric
  [✔] craftingtweaks-fabric-1.21.1-21.1.2
  [✔] CreativeCore_FABRIC_v2.12.6_mc1.21
  [✔] Creeperoverhaul-fabric-1.21-4.0.4
  [✔] cristellib-fabric-1.2.7
  [✔] Croptopia-1.21-FABRIC-3.0.9
  [✔] cubes-without-borders-2.1.1+1.21
  [✔] cullleaves-fabric-3.4.0
  [✔] cupboardfabric-1.21-2.7
  [✔] custom-crosshair-mod-v1.6.0-fabric-mc1.21.1
  [✔] custom-portals-3.6.1-1.21
  [✔] dark-loading-screen-1.6.14
  [✔] darkquesting-fabric-1.21-1.2.7
  [✔] darkrtp-fabric-1.21-1.1.9
  [✔] darktimer-fabric-1.21-1.2.1
  [✔] deeperdarker-fabric-1.21-1.3.1
  [✔] DisableAccessibilityScreen-1.0.1
  [✔] does_it_tick-fabric-1.0.0-1.21.1
  [✔] dragonloot-1.1.6
  [✔] duckling-fabric-1.21-5.0.1
  [✔] ducky-updater-rework-2024.7.1-1.20
  [✔] dungeons-and-taverns-v4.3
  [✔] dungeons+-1.8.4b
  [✔] DungeonsArise-1.21.x-2.1.60-fabric-release
  [✔] DungeonsAriseSevenSeas-1.21.x-1.0.3-fabric
  [✔] dynamic-fps-3.6.3+minecraft-1.21.0-fabric
  [✔] e4mc_minecraft-5.1.0
  [✔] earth2java-fabric-1.11.5+1.21
  [✔] eating-animation-1.21+1.9.72
  [✔] EffectTimerPlus-Fabric-1.21-2.2.1
  [✔] elementalenchantments-2.0.1
  [✔] elytra_trinket-1.0.9
  [✔] EmeraldTools-Fabric-1.21.1-1.8.16
  [✔] enchantments-encore-1.7c
  [✔] endrem-fabric-1.21.X-6.0.2
  [✔] enhancedblockentities-0.10.1+1.21
  [✔] entityculling-fabric-1.6.7-mc1.21
  [✔] EpheroLib-FABRIC-1.2.0-1.21
  [✔] Epic Dungeons-0.1.04-Fabric-1.21
  [✔] EquipmentCompare-1.21-fabric-1.3.12
  [✔] Essential Dependencies
  [✔] essential_1-3-4_fabric_1-21-1
  [✔] expanded_ecosphere-fabric-3.4.0
  [✔] expandedstorage-fabric-1.21-14.1.1
  [✔] ExpandedWorld-v1.3.0
  [✔] ExplorersCompass-1.21-2.2.5-fabric
  [✔] explosive-enhancement-1.2.3-1.21.0
  [✔] extended-enchanting-2.0.0+1.21
  [✔] extra-damage-enchantments-2.0.0+1.21
  [✔] extshape_blockus-fabric-2.2.2-mc1.21.1
  [✔] extshape-fabric-2.2.2-mc1.21.1
  [✔] fabric_medieval_buildings_end_edition-1.0.2-1.21
  [✔] fabric_medieval_buildings-1.0.2-1.21
  [✔] fabric-api-0.102.1+1.21.1
  [✔] fabric-language-kotlin-1.12.1+kotlin.2.0.20
  [✔] fabric-luckytntlib-1.21-0.100.6.1
  [✔] fabric-luckytntmod-1.21-6.0
  [✔] FancyBlockParticles-1.21-fabric-21.0.0.2-beta
  [✔] fast-ip-ping-mc1.21-fabric-v1.0.3
  [✔] fastasyncworldsave-fabric-1.21-2.0
  [✔] fastercrouching-1.21.1-2.6
  [✔] fastquit-3.0.0+1.20.6
  [✔] ferritecore-7.0.0-fabric
  [✔] fireoverlaycontroller-1.0+1.19.3
  [✔] fish_of_thieves-mc1.21-v4.0.1-fabric
  [✔] flowerymooblooms-fabric-mc1.21-2.0.2
  [✔] foodtxf-1.21.1-1.7.2-fabric
  [✔] ForgeConfigAPIPort-v21.1.0-1.21.1-Fabric
  [✔] forgivingvoid-fabric-1.21.1-21.1.1
  [✔] formations-1.0.2-fabric-mc1.21
  [✔] formationsnether-1.0.5-mc1.21+
  [✔] formationsoverworld-1.0.4-mc1.21+
  [✔] friendsandfoes-fabric-mc1.21-2.0.16
  [✔] fullstackwatchdog-1.0.1+1.19.2-fabric
  [✔] geckolib-fabric-1.21.1-4.6
  [✔] GlitchCore-fabric-1.21.1-2.1.0.0
  [✔] glore-1.21.x-1.4.0
  [✔] Gobber2-Fabric-1.21.1-2.10.27
  [✔] GreaterEye-Fabric-1.21.1-1.7.7
  [✔] grind-enchantments-3.2.2+1.21-rc1
  [✔] GrowableOres-2.4.1-1.21-Fabric
  [✔] guardvillagers-2.1.2-1.21
  [✔] handcrafted-fabric-1.21.1-4.0.2
  [✔] Highlighter-1.21-fabric-1.1.11
  [✔] HopoBetterMineshaft-[1.21]-1.2.7
  [✔] HopoBetterRuinedPortals-[1.21]-1.4.3
  [✔] HopoBetterUnderwaterRuins-[1.21]-1.2.0b
  [✔] Iceberg-1.21-fabric-1.2.5
  [✔] iChunUtil-1.21-Fabric-1.0.0
  [✔] ImmediatelyFast-Fabric-1.2.20+1.21.1
  [✔] immersive-structures-2.2.0
  [✔] ImmersiveUI-FABRIC-0.2.2
  [✔] ingotcraft-1.21.1-2.4.5-fabric
  [✔] inventorytotem-1.21.1-3.3
  [✔] InvMove-1.21-0.8.8-Fabric
  [✔] InvMoveCompats-1.20-0.3.2-Fabric
  [✔] iris-fabric-1.8.0-beta.2+mc1.21.1
  [✔] ItemBorders-1.21-fabric-1.2.5
  [✔] justenoughbreeding-fabric-1.21.x-1.2.5
  [✔] katters-structures-2.0
  [✔] knightquest-1.5.1
  [✔] krypton-0.2.8
  [✔] language-reload-1.6.1+1.21
  [✔] LegendaryTooltips-1.21-fabric-1.4.11
  [✔] letmedespawn-1.3.1
  [✔] libz-1.0.3
  [✔] lightweight-inventory-sorting-1.1.2+1.21
  [✔] limitedchunks-fabric-1.21-4.1
  [✔] lithium-fabric-mc1.21.1-0.13.0
  [✔] lithosphere-1.2
  [✔] lithostitched-fabric-1.21-1.2.5a
  [✔] lmft-1.0.4+1.21-fabric
  [✔] lukis-grand-capitals-1.0
  [✔] macawsbridgesbop-fabric-1.21-1.0
  [✔] macawsroofsbop-fabric-1.21-1.0
  [✔] mavapi-fabric-1.2.1-mc1.21
  [✔] mavm-fabric-1.3.0-mc1.21
  [✔] mcw-bridges-3.0.0-mc1.21.1fabric
  [✔] mcw-doors-1.1.1-mc1.21.1fabric
  [✔] mcw-fences-1.1.2-mc1.21.1fabric
  [✔] mcw-furniture-3.3.0-mc1.21.1fabric
  [✔] mcw-holidays-1.1.0-mc1.21.1fabric
  [✔] mcw-lights-1.1.1-mc1.21.1fabric
  [✔] mcw-paths-1.0.5-1.21.1fabric
  [✔] mcw-roofs-2.3.1-mc1.21.1fabric
  [✔] mcw-trapdoors-1.1.3-mc1.21.1fabric
  [✔] mcw-windows-2.3.0-mc1.21.1fabric
  [✔] mcwfencesbop-fabric-1.21-1.1
  [✔] mcwfurnituresbop-fabric-1.21.1-1.0
  [✔] mes-1.3.2-1.21
  [✔] methane-3.8.2
  [✔] midnightlib-fabric-1.6.0
  [✔] mine-treasure-1.4.6
  [✔] mineralchance-1.21.1-3.7
  [✔] minerally-1.21-1.21
  [✔] mixintrace-1.1.1+1.17
  [✔] mns-1.0.2-1.21
  [✔] mobs_of_mythology-fabric-1.21-2.0.4
  [✔] modelfix-1.21-1.6-fabric
  [✔] modernfix-fabric-5.19.3+mc1.21.1
  [✔] modmenu-11.0.2
  [✔] modmenu-badges-lib-2023.6.1
  [✔] monolib-fabric-1.21-1.3.0
  [✔] moonlight-1.21-2.14.12-fabric
  [✔] more_armor_trims-1.3.2-1.21
  [✔] more_beautiful_torches-merged-1.21-3.0.0
  [✔] more_bows_and_arrows-merged-1.21-3.1.0
  [✔] more_mobs-v1.5.2-mc1.14x-1.21x-mod
  [✔] MoreBarrelVariants-1.6.0+1.21-Fabric
  [✔] MoreBedVariants-1.3.0+1.21-Fabric
  [✔] MoreBeehiveVariants-1.0.0+1.21-Fabric
  [✔] MoreCartographyTables-1.5.7+1.21-Fabric
  [✔] MoreChestVariants-1.5.6+1.21-Fabric
  [✔] MoreChiseledBookshelfVariants-1.6.0+1.21.1-Fabric
  [✔] MoreComposterVariants-1.6.3+1.21-Fabric
  [✔] moreculling-1.21-0.26.0
  [✔] MoreFletchingTables-1.5.7+1.21-Fabric
  [✔] MoreFurnaceVariants-1.0.3+1.21-Fabric
  [✔] MoreGems-Fabric-1.21.1-1.7.19
  [✔] MoreLecternVariants-1.6.0+1.21.1-Fabric
  [✔] MoreLoomVariants-1.0.0+1.21-Fabric
  [✔] moremobvariants-fabric+1.21-1.3.1.1
  [✔] moreores+-2.4.1+1.21.1
  [✔] MoreShieldVariants-1.2.0+1.21-Fabric
  [✔] MoreSmithingTables-1.1.0+1.21-Fabric
  [✔] MoreSmokerVariants-1.1.0+1.21-Fabric
  [✔] MoreTotems-fabric-1.21-2.20.1
  [✔] morevanillashields-1.0.0-1.21.1
  [✔] MouseTweaks-fabric-mc1.21-2.26
  [✔] MRU-1.0.2+1.21+fabric
  [✔] mss-1.1.2-1.21
  [✔] mvs-4.1.3-1.21
  [✔] mythicmetals-0.20.1+1.21
  [✔] mythicmetals-decorations-0.7.0+1.21
  [✔] mythicupgrades-4.1.4+mc1.21
  [✔] NaturesCompass-1.21-2.2.6-fabric
  [✔] NE-1.21.1-1.9.2
  [✔] nemos-creatures-1.6.4-1.21.1
  [✔] neoenchant-5.6.0
  [✔] Neruina-2.1.1-fabric+1.21
  [✔] netherdepthsupgrade-fabric-3.1.7-1.21
  [✔] netheriteextras-0.4.0+mc1.21
  [✔] netherportalfix-fabric-1.21.1-21.1.1
  [✔] new_shield_variants-merged-1.21-1.3.0
  [✔] nice-mobs-remastered-2.5
  [✔] no-resource-pack-warnings-1.3.0
  [✔] NoChatReports-FABRIC-1.21-v2.8.0
  [✔] noisium-fabric-2.3.0+mc1.21-1.21.1
  [✔] Not Enough Recipe Book-FABRIC-0.4.1
  [✔] notenoughanimations-fabric-1.7.5-mc1.21
  [✔] notenoughcrashes-4.4.8+1.21-fabric
  [✔] Nullscape_1.21_v1.2.7
  [✔] OctoLib-FABRIC-0.4.2
  [🖿] old (folder)
  [✔] owo-lib-0.12.11+1.21
  [✔] packedup-1.0.30c-fabric-mc1.21
  [✔] paginatedadvancements-2.4.2
  [✔] passiveshield-1.21.1-3.6
  [✔] Philips-Ruins1.21.1-1.6[Fabric]
  [✔] polymorph-fabric-1.0.4+1.21
  [✔] potionring-fabric-1.21-1.0
  [✔] Prism-1.21-fabric-1.0.9
  [✔] progressivearchery-1.2.1-1.21+trinkets
  [✔] qraftyfied-8.1.1
  [✔] Quad-1.2.7+1.21-Fabric
  [✔] randomore-1.3.0
  [✔] RandomRing-Fabric-1.21.1-1.4.9
  [✔] real-arrow-tip-0.1.1+mc1.21.0
  [✔] realmsfix-2.0.5
  [✔] recipeessentials-fabric-1.21-3.7
  [✔] reeses-sodium-options-fabric-1.8.0-beta.2+mc1.21.1
  [✔] refined-advancements-1.0.4a
  [✔] reinforced-barrels-2.5.1+1.21
  [✔] reinforced-chests-3.0.1+1.21
  [✔] remove-terralith-intro-message-1.1
  [✔] repurposed_structures_friends_and_foes_compat_v8
  [✔] repurposed_structures-7.5.9+1.21.1-fabric
  [✔] resourcefulconfig-fabric-1.21-3.0.3
  [✔] resourcefullib-fabric-1.21-3.0.9
  [✔] ResourcefulTools-Fabric-1.21.1-1.6.12
  [✔] RoughlyEnoughItems-16.0.754-fabric
  [✔] RoughlyEnoughProfessions-fabric-1.21-4.0.1
  [✔] rrls-5.0.7+mc1.21-fabric
  [✔] sassot-1.2.1-1.21
  [✔] SereneSeasons-fabric-1.21.1-10.1.0.0
  [✔] servercore-fabric-1.5.4+1.21
  [✔] shulkerboxtooltip-fabric-5.1.0+1.21.1
  [✔] sihywtcamd-1.10.4+1.21
  [✔] simple-armor-hud-1.21-1.4.5
  [✔] Simple-Block-Overlay 1.21-fabric-1.4.3
  [✔] SimpleCopperPipes-2.0
  [✔] skinlayers3d-fabric-1.6.7-mc1.21
  [✔] SmartBrainLib-fabric-1.21.1-1.15
  [✔] smarterfarmers-1.21-2.0.1-fabric
  [✔] smoothchunk-fabric-1.21-3.6
  [✔] smoothscroll-2.1.2-1.21
  [✔] SmoothScrollingRefurbished+1.21-1.1.4
  [✔] snow-pig-4.0.2
  [✔] sodium-extra-fabric-0.6.0-beta.1+mc1.21.1
  [✔] sodium-fabric-0.6.0-beta.1+mc1.21
  [✔] solid_mobs_fabric.1.21-1.7.1
  [✔] sound-physics-remastered-fabric-1.21.1-1.4.6
  [✔] Sounds-2.0.4+1.21+fabric
  [✔] spawners-drop-treasure-1.0.0
  [✔] StackDeobfuscatorFabric-1.4.3+08e71cc
  [✔] strange-berries-2.5-1.21
  [✔] strayed-fates-forsaken-v2.0.0.0
  [✔] structureessentials-fabric-1.21-3.4
  [✔] styled-chat-2.6.0+1.21
  [✔] styledplayerlist-3.5.1+1.21
  [✔] supermartijn642configlib-1.1.8-fabric-mc1.21
  [✔] supermartijn642corelib-1.1.17b-fabric-mc1.21
  [✔] sushimod-v1.0.1-fabric-1.21
  [✔] swingthrough-1.0.5+1.21
  [✔] t_and_t-neoforge-fabric-1.13.2
  [✔] T6-AutoAttack-v3_Fabric-1.21.1
  [✔] TaxFreeLevels-1.3.12-fabric-1.20.5
  [✔] tcdcommons-3.12.3+fabric-1.21
  [✔] tectonic-fabric-1.21.1-2.4.1a
  [✔] TerraBlender-fabric-1.21.1-4.1.0.0
  [✔] Terralith_1.21_v2.5.4
  [✔] the_bumblezone-7.6.26+1.21.1-fabric
  [✔] TheVeggieWay_Fabric-1.21.1-1.6.10
  [✔] tidal-towns-1.3.3
  [✔] tiered-1.3.3.beta
  [✔] tool-trims-mod-v2-2-1a
  [✔] totw_modded-fabric-1.21-1.0.5
  [✔] trade-cycling-fabric-1.21.1-1.0.14
  [✔] travelersbackpack-fabric-1.21-10.0.6
  [✔] travelerscompass-1.21-3.0.5-fabric
  [✔] treeharvester-1.21.1-9.1
  [✔] trimeffects-fabric-1.21.X-1.3.5
  [✔] trinkets-3.10.0
  [✔] tru.e-ending-v1.1.2b
  [✔] tt20-0.7.0+mc1.21
  [✔] UndergroundBunkers-1.0.4-1.21.x-fabric
  [✔] UsefulFood_Reborn-1.2.4-1.21.1-Fabric
  [✔] useless-reptile-0.7.4.2-1.21
  [✔] vanilla-refresh-1.4.23b_1.21
  [✔] vanillablocksplus-2.0.4
  [✔] variantsandventures-fabric-mc1.21-1.0.5
  [✔] videotape-1.3.0
  [✔] viewboboptions-0.3.0+1.21
  [✔] villagernames-1.21.1-8.1
  [✔] visuality-0.7.7+1.21
  [✔] visualoverhaul-fabric-5.2.1
  [✔] voidz-1.0.11
  [✔] wakes-0.3.0+1.21.1
  [✔] wardentools-2.5.1+mc1.21
  [✔] watut-fabric-1.21.0-1.1.3
  [✔] waystones-fabric-1.21.1-21.1.1
  [✔] WilderWild-2.4.15-mc1.21.1
  [✔] wits-1.3.0+1.21-fabric
  [✔] worldweaver-21.0.13
  [✔] wthit-fabric-12.4.0
  [✔] XaeroPlus-2.22.3+fabric-1.21-WM1.39.0-MM24.3.0
  [✔] Xaeros_Minimap_24.3.0_Fabric_1.21
  [✔] XaerosWorldMap_1.39.0_Fabric_1.21
  [✔] xtraarrows-3.4.2-fabric-mc1.21
  [✔] YetAnotherConfigLib-3.5.0+1.21-fabric
  [✔] yggdrasil-structure-1.4.0
  [✔] youre-in-grave-danger-fabric-2.4.7
  [✔] Zoomify-2.14.0+1.21

### Logs

https://mclo.gs/dnKuton

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Confirmed the crash when TNT is present. Will fix next update.

**Comment by VaporeonScripts** [comment]
alright, thank you!
