### ISSUE TITLE
Modrinth Page?

### ISSUE THREAD

**Issue by PolyframeX** [MehVahdJukaar/FarmersDelightRefabricated#7]
Would it be possible for a modrinth page to be opened? It would help significantly with accessibility of the mod.

**Comment by MehVahdJukaar** [comment]
modrinth takes ages to approve newprojects

**Comment by ChrysanthCow** [comment]
It's on the way ^^

**Comment by ChrysanthCow** [comment]
We've just fixed the issues we were having whilst uploading to Modrinth. So hopefully it'll be rereviewed soon.

**Comment by ChrysanthCow** [comment]
# [Approved!](https://modrinth.com/mod/farmers-delight-refabricated)
