### ISSUE TITLE
Crops and seeds aren't compostable

### ISSUE THREAD

**Issue by pajicadvance** [MehVahdJukaar/FarmersDelightRefabricated#73]
### Minecraft version

1.21

### Farmer's Delight version

1.21-2.1.6+refabricated

### Fabric Loader version

0.16.3

### Fabric API version

0.102.0+1.21

### Description

Crops and seeds added by the mod are not usable in the composter, contrary to vanilla crops and seeds.

### Steps to reproduce

Try using any crop or seed from the mod on the composter. It does not work.

### Mod list

[✔] fabric-api-0.102.0+1.21
[✔] FarmersDelight-1.21-2.1.6+refabricated

### Logs

https://mclo.gs/CxhDR2V

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by retropele** [comment]
I've still found this to be the case on 1.19.2, is it only rectified in newer versions?

**Comment by ChrysanthCow** [comment]
1.19.2 is not supported by us. That's the old archived port.
