### ISSUE TITLE
Farmer's delight

### ISSUE THREAD

**Issue by macuguita** [MehVahdJukaar/FarmersDelightRefabricated#8]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.5

### Forge version

Quilt 0.24.0

### Description

My server crashes whenever it tries to generate stuff related to farmers delight

### Mod list

- Supplementaries
- Extra Origins
- Another Furniture
- Mob Origins
- Dramatic Doors
- No Chat Reports
- oωo
- MidnightLib
- EnchantmentDescriptions
- Athena
- Extra Alchemy
- Bookshelf
- Glass Armor
- Farmer's Delight
- Cosmetic Armor
- Resourceful Lib
- Decorative Blocks
- Origins: Classes
- GeckoLib 4
- Ecologics
- Just Enough Items
- Respawnable Pets
- Apugli
- Supplementaries Squared
- Pehkui
- Simple Voice Chat
- Universal Graves
- Origins
- Regions Unexplored
- BeansBackpacks
- TerraBlender
- AppleSkin
- Amendments
- More Mob Variants
- Naturalist
- Quilted Fabric API
- Trinkets
- Smarter Farmers
- Moonlight
- The Bumblezone - Fabric
- Cave Dweller Fabric
- Handcrafted
- Force Crawl
- Perfect Plushies
- Joy of Painting
- Polymorph
- Bad Packets
- Chipped

### Logs

https://mclo.gs/6uW2d14

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Fixed in 2.0.7.
