### ISSUE TITLE
Game crashing on 1.21 because of: mouseClicked event handler

### ISSUE THREAD

**Issue by SecretiXz** [MehVahdJukaar/FarmersDelightRefabricated#80]
### Minecraft version

1.21

### Farmer's Delight version

2.1.7

### Fabric Loader version

0.16.3

### Fabric API version

0.102.0

### Description

When clicking "disconnect" button while playing on server (farmer's delight is installed on the server too), the game crashes, saying mouseClicked event handler

### Steps to reproduce

1. Joined moded server that has farmer's delight in
2. Pressing "Disconnect" button
3. Crashing 

### Mod list

Fabric Mods: 
		advancementinforeloaded: AdvancementInfo Reloaded 0.4.1-1.21
		ambientsounds: AmbientSounds 6.0.5
		amplified_nether: Amplified Nether 1.2.5
		animatica: Animatica 0.6.1+1.21
		architectury: Architectury 13.0.6
		auditory: Auditory 0.0.7-1.21
		betterf3: BetterF3 11.0.1
		bobby: Bobby 5.2.4+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		chat_heads: Chat Heads 0.12.13
		cherishedworlds: Cherished Worlds 10.0.2+1.21.1
		clickthrough: ClickThrough 1.21
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		connectiblechains: Connectible Chains 2.4.2+1.21.1
		creativecore: CreativeCore 2.12.6
			net_neoforged_bus: bus 7.2.0
		cullleaves: Cull Leaves 3.4.0
			midnightlib: MidnightLib 1.5.7
		dark-loading-screen: Dark Loading Screen 1.6.14
		dense-flowers: Dense Flowers 0.1.1+mc1.21.0
		eatinganimationid: Eating Animation 1.21+1.9.72
		elytratrims: Elytra Trims 3.4.4
			conditional-mixin: conditional mixin 0.6.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.2
		farmersdelight: Farmer's Delight 1.21-2.1.7+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta+fdrf.1+1.21
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta+fdrf.1+1.21
				porting_lib_asm: Porting Lib ASM 3.1.0-beta+fdrf.1+1.21
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta+fdrf.1+1.21
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta+fdrf.1+1.21
				porting_lib_common: Porting Lib Common 3.1.0-beta+fdrf.1+1.21
				porting_lib_entity: Porting Lib Entity 3.1.0-beta+fdrf.1+1.21
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta+fdrf.1+1.21
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta+fdrf.1+1.21
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta+fdrf.1+1.21
			porting_lib_config: Porting Lib Config 3.1.0-beta+fdrf.1+1.21
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta+fdrf.1+1.21
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta+fdrf.1+1.21
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta+fdrf.1+1.21
				porting_lib_core: Porting Lib Core 3.1.0-beta+fdrf.1+1.21
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta+fdrf.1+1.21
			porting_lib_loot: Porting Lib Loot 3.1.0-beta+fdrf.1+1.21
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta+fdrf.1+1.21
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta+fdrf.1+1.21
		ferritecore: FerriteCore 7.0.0
		held-item-info: Held Item Info 1.7.0
		immersiveui: ImmersiveUI 0.1.1
		indium: Indium 1.0.34+mc1.21
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lithium: Lithium 0.12.7
		mace3d: 3D Mace 1.0.1
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
		mousetweaks: Mouse Tweaks 2.26
		noisium: Noisium 2.2.1+mc1.21
		notenoughanimations: NotEnoughAnimations 1.7.4
		nullscape: Nullscape 1.2.7
		nvidium: Nvidium 0.2.9-beta
		obsidianui: ObsidianUI 0.2.7+mc1.21
		octolib: OctoLib 0.4.2
			org_yaml_snakeyaml: snakeyaml 2.2
		ok-boomer: Ok Boomer 0.1.4+1.21
		owo: oωo 0.12.11+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		particlerain: Particle Rain 2.1.2
		placeholder-api: Placeholder API 2.4.1+1.21
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		replantingcrops: Replanting Crops 5.4
		replaymod: Replay Mod 1.21-2.6.17
		roughlyenoughitems: Roughly Enough Items 16.0.744
			error_notifier: Error Notifier 1.0.9
		ryoamiclights: RyoamicLights 0.2.11+mc1.21.1
		skinlayers3d: 3d-Skin-Layers 1.6.6
		smoothscroll: Smooth Scroll 2.1.2
		sodium: Sodium 0.5.11+mc1.21
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.3
		terralith: Terralith 2.5.4
		voicechat: Simple Voice Chat 1.21-2.5.19
		wakes: Wakes 0.2.5+1.21
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		wildfire_gender: Wildfire's Female Gender Mod 3.2.1+1.21
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

### Logs

server log
[latest.log](https://github.com/user-attachments/files/16847243/latest.log)
client log
[latest.log](https://github.com/user-attachments/files/16847256/latest.log)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
The offending code has changed in the latest version.
