### ISSUE TITLE
Mixin Transformation Failure

### ISSUE THREAD

**Issue by TheIrishStud** [MehVahdJukaar/FarmersDelightRefabricated#83]
### Minecraft version

1.21

### Farmer's Delight version

1.21-2.1.7

### Fabric Loader version

0.15.11-1.21

### Fabric API version

0.100.4+1.21

### Description

Game crashes before I even get a chance to test anything... All that is provided below is straight from the crash log.... Will go to pastebin or comment further if more information is needed or required for crash reproduction.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-09-05 05:26:39
Description: Bootstrap

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2315 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:52)
	at net.minecraft.client.main.Main.main(Main.java:130)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for farmersdelight.mixins.json:CuttingBoardDispenserMixin from mod farmersdelight during activity: [Transform -> Method onCuttingBoardDispenseFromInject(Lnet/minecraft/class_3218;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_2601;Lnet/minecraft/class_2342;ILnet/minecraft/class_1799;)V -> INVOKEVIRTUAL -> io/github/fabricators_of_create/porting_lib/config/ModConfigSpec$BooleanValue::get:()Ljava/lang/Object;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.config.ModConfigSpec$BooleanValue
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 19 more
Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.config.ModConfigSpec$BooleanValue
	... 23 more

### Steps to reproduce

Add the mods to the mod folder and try to launch the game.

### Mod list

ash_api: Ash API 21.0.1-beta
		autofish: AFKfish 0.6
			cloth-config: Cloth Config v15 15.0.127
				cloth-basic-math: cloth-basic-math 0.6.1
		badpackets: Bad Packets 0.8.1
		balm-fabric: Balm 21.0.8
			kuma_api: KumaAPI 21.0.4
		betterf3: BetterF3 11.0.1
		betterstats: Better Statistics Screen 3.11.2+fabric-1.21
		betterthirdperson: Better Third Person 1.9.0
		blocky-bubbles: Blocky Bubbles 1.2.1+1.21.1
		bowinfinityfix: Bow Infinity Fix 3.1.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.104+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.104+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.104+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.104+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.104+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.104+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.104+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.104+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.104+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.104+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.104+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.104+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.104+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.104+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.104+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.104+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.104+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.104+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.104+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.104+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.104+1.21
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		collective: Collective 7.67
		continuity: Continuity 3.0.0-beta.5+1.21
		debugify: Debugify 1.21+1.0
		doubledoors: Double Doors 5.8
		fabric-api: Fabric API 0.100.4+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.15+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.2+78017270d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.9+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.11+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.23+78017270d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.80+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
		farmersdelight: Farmer's Delight 1.21-2.1.7+refabricated
			mm: Manningham Mills 2.3
		farmingforblockheads: Farming for Blockheads 21.0.2
		fence_on_slab: Fence On Slab! 1.0.0
		ferritecore: FerriteCore 7.0.0
		firehud: Fire Hud 1.1.1-1.21
		forcecrawl: Force Crawl 1.0.4
		grassseeds: Grass Seeds 3.2
		gravestones: Gravestones 1.0.6
		indium: Indium 1.0.34+mc1.21
		infinite_bundle: Infinite Storage Bundle 4
		inventorytotem: Inventory Totem 3.2
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.0.0.9
		justmobheads: Just Mob Heads 8.1
		kiwi: Kiwi Library 15.1.0+fabric
		kleeslabs: KleeSlabs 21.0.2
		letmedespawn: Let Me Despawn 1.3.0
		lithium: Lithium 0.13.0
		lolmblv: More Barrel Variants 1.5.3
		lolmcgt: More Cartography Tables 1.5.3
		lolmcmv: More Composter Variants 1.5.3
		lolmcv: More Chest Variants 1.5.6
		lolmlv: More Lectern Variants 1.5.3
		minecraft: Minecraft 1.21
		minecraftcapes: MinecraftCapes 12.3.8
		mineralchance: Mineral Chance 3.6
		modelfix: Model Gap Fix 1.21-1.6
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moveboats: Move Boats 3.3
		mr_better_bundle: Better Bundle 1.4.1+1.21
		mr_craftable_bundles: Craftable Bundle 48.1
		mr_dyeable_bundles: Colored Bundles 48.1.34.1
		mr_ketkets_furnicraft: FurniCraft 3.1
		mr_leather_bundles1: Leather Bundles 1.1
		mr_more_blocks: More Blocks 1
		mr_oldschool_netherite: Oldschool Netherite 1.2
		netherportalfix: NetherPortalFix 21.0.2
		nodurability: No Durability 2.0.0
		nohunger: No Hunger 1.3.1
			mixinextras: MixinExtras 0.3.6
		oxidized: Oxidized 1.8.3
			saflib: SafLib 1.1.1
		paperbooks: Paper Books 3.4
		pneumonocore: PneumonoCore 1.1.6
		quad: Quad 1.2.7
		randomshulkercolours: Random Shulker Colours 3.2
		replantingcrops: Replanting Crops 5.3
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.2
		shuffle: Shuffle 21.0.1
		shulkerdropstwo: Shulker Drops Two 3.3
		sixstairs: Craft 6 stairs instead of 4 1.21-10-fabric
		snowrealmagic: Snow! Real Magic! 11.0.1+fabric
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		softerhaybales: Softer Hay Bales 3.2
		spidersproducewebs: Spiders Produce Webs 3.4
		stack: stack 1.0.3
		stackrefill: Stack Refill 4.4
		stutterfix: StutterFix mc1.21-0.2.1
		tcdcommons: TCD Commons API 3.11.1+fabric-1.21
		through-the-lilypads-gently: Through the lily pads, gently 1.1.1
		tool_trims: Tool Trims 2.1.3
		vertical-slabs: Vertical slabs 2.1.0-1.21
		wthit: wthit 12.2.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by RKDeviancy** [comment]
+1. I have this same issue on the most recent file from Modrinth. Reading through your crash report it looks to be basically the same as mine, just a different mod list and system specs

**Comment by ChrysanthCow** [comment]
Porting lib is not seeming to load for some reason... Many ppl have had this issue, but I have unfortunately not no leads on what could be causing this.

**Comment by MerchantPug** [comment]
https://github.com/MehVahdJukaar/FarmersDelightRefabricated/issues/106

**Comment by ChrysanthCow** [comment]
Update to 1.21.1
