### ISSUE TITLE
 [ERROR]: type reading: crafttweaker.neoforge.api.item.ItemAbility: / :0:

### ISSUE THREAD

**Issue by QianMuu** [MehVahdJukaar/FarmersDelightRefabricated#85]
### Minecraft version

1.21

### Farmer's Delight version

1.21

### Fabric Loader version

0.16.0

### Fabric API version

fabric-api-0.102.1+1.21.1

### Description

![image](https://github.com/user-attachments/assets/79ff8162-a447-49c6-b172-ba058718824f)

### Steps to reproduce

1：Enter the game.
2：Error message appears

### Mod list

https://paste.ee/p/srXIp

### Logs

https://paste.ee/p/y3gTU

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Has been fixed in the latest update
