### ISSUE TITLE
Beetroot soup, mushroom stew & rabbit stew do not stack to 16

### ISSUE THREAD

**Issue by nkinetic** [MehVahdJukaar/FarmersDelightRefabricated#86]
### Minecraft version

1.21

### Farmer's Delight version

2.1.7

### Fabric Loader version

0.16.4

### Fabric API version

0.102.0+1.21

### Description

When picking up beetroot soups, mushroom stews or rabbit stews, they do not stack to 16 like they do in previous versions of farmer's delight.

### Mod list

Fabric API, Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Hi, i think we forgot to implement this previously. Ill go in and get this fixed later today.

**Comment by ChitoBurrito** [comment]
Will this fix be backported to 1.20.1 by any chance?

**Comment by ChrysanthCow** [comment]
> Will this fix be backported to 1.20.1 by any chance?

? I thought it worked there, weird.

**Comment by ChitoBurrito** [comment]
Am very sorry, I just checked again, and ye it works. I have a lot of instances Im trying to set up / fix and I misread some version numbers and got confused, my bad.
