### ISSUE TITLE
Tools don't stick in the cutting board

### ISSUE THREAD

**Issue by nkinetic** [MehVahdJukaar/FarmersDelightRefabricated#87]
### Minecraft version

1.21

### Farmer's Delight version

2.1.7

### Fabric Loader version

0.16.4

### Fabric API version

0.102.0+1.21

### Description

When sneak-clicking a tool onto the cutting board, it doesn't stick/carve into the surface of the cutting board like it used to in previous versions. This is the case for all tools.

### Steps to reproduce

1. Go into creative
2. Put down a cutting board
3. Sneak-click using a tool onto the cutting board
4. Cry

### Mod list

Fabric API, Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Imo, this'd likely have to be added by an addon rather than Refabricated.

I assume that this is a leftover from the old port that wasn't in the og FD.

**Comment by ChrysanthCow** [comment]
Sorry for the super late response, I just had to think for a while about this, and then I forgot to reply.
