### ISSUE TITLE
Fabric 1.20.1 farmersdelight-common.toml is not correct.

### ISSUE THREAD

**Issue by Gamerbolts** [MehVahdJukaar/FarmersDelightRefabricated#89]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.6

### Fabric Loader version

0.16.5

### Fabric API version

0.92.2+1.20.1

### Description

I am creating a modpack actually a couple of them and noticed when running a server with Farmer's Delight in it it would cause a message to be spammed constantly. I have provided the log. The server will not start. I can't close it and have to crash the server in order to stop it. It says JEI in the log however I have REI.

### Steps to reproduce

My modpack is not available publicly. I would think putting REI (Roughly Enough Items) with Farmer's Delight Refabricated would produce the same problem.

### Mod list

https://pastebin.com/4L3jJS6t

### Logs

https://pastebin.com/dgvsSeUT

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
Try regenerating your config and starting from there. This seems to be an issue with your config.

**Comment by Gamerbolts** [comment]
Hmm I tried that. No luck

**Comment by ChrysanthCow** [comment]
Could i see your config file?

**Comment by Gamerbolts** [comment]
[farmersdelight-common-2.toml.zip](https://github.com/user-attachments/files/16985897/farmersdelight-common-2.toml.zip)
Here you go!

**Comment by ChrysanthCow** [comment]
The zip is invalid.

**Comment by Gamerbolts** [comment]
Sorry, dumb github lol. I will put them into pastebin
farmersdelight-common.toml - https://pastebin.com/5fDPhh2L
farmersdelight-common-1.toml.bak - https://pastebin.com/hGbDmfgM
farmersdelight-common-2.toml.bak - https://pastebin.com/Jr9dYnGw
farmersdelight-common-3.toml.bak - https://pastebin.com/k9Xhstn6
farmersdelight-common-4.toml.bak - https://pastebin.com/4VJXhV6N
farmersdelight-common-5.toml.bak - https://pastebin.com/YhKyxTNC

That is all the farmers delight config files in my config folder. Hope it helps

**Comment by ChrysanthCow** [comment]
Hi, you have copied a completely different config at the top of the Farmer's Delight config. I'd recommend you remove the lines that are there, and then it should be fixed.

**Comment by ChrysanthCow** [comment]
```
#A list of class:method strings (render methods) that the dark shader will not be applied to.
#Each string consists of the class and the method (or any substring) to block the dark shader.
#For example, 'renderHunger' is sufficient to block 'net.minecraftforge.client.gui.overlay.ForgeGui:renderFood' (either will work).
METHOD_SHADER_BLACKLIST = ["mezz.jei.common.render.FluidTankRenderer:drawTextureWithMasking", "mezz.jei.library.render.FluidTankRenderer:drawTextureWithMasking", "renderCrosshair", "m_93080_", "renderSky", "m_202423_", "renderHotbar", "m_93009_", "m_193837_", "setupOverlayRenderState", "net.minecraftforge.client.gui.overlay.ForgeGui", "renderFood", "renderExperienceBar", "m_93071_", "renderLogo", "m_280037_", "m_280118_", "net.minecraft.client.gui.Gui", "net.minecraft.src.C_3431_", "renderDirtBackground", "m_280039_", "m_280039_", "configured.client.screen.ListMenuScreen", "OnlineServerEntry:drawIcon", "OnlineServerEntry:m_99889_", "WorldSelectionList$WorldListEntry:render", "WorldSelectionList$WorldListEntry:m_6311_", "CubeMap:render", "CubeMap:m_108849_", "squeek.appleskin.client.HUDOverlayHandler", "shadows.packmenu.ExtendedMenuScreen"]
#Enabling this config will (every 5 seconds) dump which methods were used to render GUIs that the dark shader was applied to
#The dump will consist of a list of class:method strings, e.g. 'net.minecraftforge.client.gui.overlay.ForgeGui:renderFood'
#Use this feature to help find the render method strings of GUIs you would like to blacklist.
METHOD_SHADER_DUMP = false
"Inventory Button" = {}
```

Delete all this.

**Comment by Gamerbolts** [comment]
ok I will attempt this. I am not sure why it did that I didn't do it manually. I did at one point have addons for farmers delight, could that have caused this? Also do I delete the 5 other config files? I'll get this done tomorrow and let you know if it fixes things. Thanks!

**Comment by Gamerbolts** [comment]
ok I removed that from the config file, then started the server back up and it readded it back. Also I noticed while it is spamming that text to the log, the 1-5.bak files are constantly removing themselves and readding to the config folder
[latest.log](https://github.com/user-attachments/files/16993029/latest.log)
Latest log

**Comment by ChrysanthCow** [comment]
that's a Porting Lib Forge config system port issue, not really something we can treat.

**Comment by ChrysanthCow** [comment]
Im going to close this as not planned, because I have zero clue on how this can be fixed.

**Comment by Gamerbolts** [comment]
Odd enough as this may seem, the issue was the Dark Mode Everywhere mod. For anyone else having the same issue
