### ISSUE TITLE
Kiwi Crash with Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by ereese99** [MehVahdJukaar/FarmersDelightRefabricated#9]
### Minecraft version

1.20.1

### Farmer's Delight version

2.0.7

### Forge version

Fabric 0.15.7

### Description

Crashes upon loading

### Steps to reproduce

1. Have Farmer's Delight Refabricated
2. Have Kiwi
3. Try to play Minecraft

### Mod list

You can see the modlist in the crash log in the "logs" section

Note: It might not be "Kiwi" but rather one of their mods, considering the crash does not occur on a "minimal instance (just the 2 mods)"

### Logs

[crash-2024-03-28_10.47.36-client.txt](https://github.com/MehVahdJukaar/FarmersDelight/files/14791393/crash-2024-03-28_10.47.36-client.txt)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ereese99** [comment]
Found the root : Fruitful Fun

I tested it on a minimal instance: Farmer's Delight Refabricated, Fruitful Fun, Kiwi, Lychee

It crashed

**Comment by ereese99** [comment]
[crash-2024-03-28_11.02.25-client.txt](https://github.com/MehVahdJukaar/FarmersDelight/files/14791554/crash-2024-03-28_11.02.25-client.txt)

**Comment by JLUsr** [comment]
> Found the root : Fruitful Fun
> 
> I tested it on a minimal instance: Farmer's Delight Reated, Fruitful Fun, Kiwi, Lychee
> 
> It crashed


Fruitful Fun has Farmers Delight integration for `Farmer's Delight ` not `Farmer's Delight Reated` (this mod).
This is an issue with Fruitful Fun, I would suggest closing this issue here and referencing it in a post in [their repo](https://github.com/Snownee/FruitfulFun/issues?q=is%3Aissue) should you wish to request compatibility with them.
