### ISSUE TITLE
Incompatibility help

### ISSUE THREAD

**Issue by heymeghan** [MehVahdJukaar/FarmersDelightRefabricated#90]
### Minecraft version

1.20.6

### Farmer's Delight version

2.1.6

### Fabric Loader version

0.16.5

### Fabric API version

0.100.8+1.20.6

### Description

when attempting to launch 1.20.6 minecraft i get this error. 
![image](https://github.com/user-attachments/assets/176cdcb3-afe2-42d7-94ef-9cd8fbaef6e3)
I have tried dowloading multiple versions to no avail. can anyone please help me? 

### Mod list

Mods:
  [✔] AmbientSounds_FABRIC_v6.0.2_mc1.20.6
  [✔] appleskin-fabric-mc1.20.5-3.0.5
  [✔] architectury-12.1.4-fabric
  [✔] betterstats-3.12.6+fabric-1.20.6
  [✔] camerautils-fabric-1.20.6-1.0.12
  [✔] carryon-fabric-1.20.6-2.1.4.21
  [✔] Chunky-1.4.10
  [✔] cloth-config-14.0.139-fabric
  [✔] Clumps-fabric-1.20.6-17.0.0.1
  [✔] collective-1.20.6-7.84
  [✔] comforts-fabric-8.0.1+1.20.6
  [✔] continuity-3.0.0-beta.5+1.20.5
  [✔] Controlling-fabric-1.20.6-17.0.1
  [✔] craftsaddles-v1.2.0-fabric-1.20.5-1.20.6
  [✔] cratedelight-24.09.03-1.20-fabric
  [✔] CreativeCore_FABRIC_v2.11.33_mc1.20.6
  [✔] dark-loading-screen-1.6.14
  [✔] doubledoors-1.20.6-5.9
  [✔] durabilitytooltip-1.1.5-fabric-mc1.20.6
  [✔] eating-animation-1.20.6+1.9.7
  [✔] expandeddelight-0.3.2
  [✔] fabric-api-0.100.8+1.20.6
  [✔] fabric-installer-1.0.1
  [✔] fabric-language-kotlin-1.12.2+kotlin.2.0.20
  [✔] fallingleaves-1.15.9+1.20.5
  [✔] FallingTree-1.20.6-1.20.6.8
  [✔] FarmersDelight-1.20.1-2.1.6+refabricated
  [✔] flow-2.1.2+1.20.6
  [✔] ForgeConfigAPIPort-v20.6.1-1.20.6-Fabric
  [✘] hauntedharvest-1.20-3.1.22-fabric.jar (disabled)
  [✔] indium-1.0.34+mc1.20.1
  [✔] InventoryProfilesNext-fabric-1.20.6-2.0.2
  [✔] iris-1.7.2+mc1.20.6
  [✔] jamlib-fabric-1.0.9+1.20.6
  [✔] jei-1.20.1-fabric-15.19.5.99
  [✔] journeymap-1.20.1-5.10.2-fabric
  [✔] jumpoverfences-fabric-1.20.4-1.5.0
  [✔] JustEnoughResources-Fabric-1.20.6-1.5.1.10
  [✔] konkrete_fabric_1.9.4_MC_1.20.5
  [✔] libIPN-fabric-1.20.6-6.0.0
  [✔] mcw-bridges-3.0.0-mc1.20.6fabric
  [✔] mcw-doors-1.1.1fabric-mc1.20.6
  [✔] mcw-fences-1.1.2-mc1.20.6fabric
  [✔] mcw-furniture-3.3.0-mc1.20.6fabric
  [✔] mcw-lights-1.1.1-mc1.20.6fabric
  [✔] mcw-paths-1.0.5-1.20.6fabric
  [✔] mcw-roofs-2.3.1-mc1.20.6fabric
  [✔] mcw-trapdoors-1.1.3-mc1.20.6fabric
  [✔] mcw-windows-2.3.2-mc1.20.6fabric
  [✔] modmenu-10.0.0
  [✔] moonlight-1.20-2.5.10-fabric
  [✔] MRU-1.0.2+1.20.6+fabric
  [✔] no-creeper-grief-v.0.3.0
  [✔] noisium-fabric-2.3.0+mc1.20.5-1.20.6
  [✔] placeholder-api-2.4.0-pre.1+1.20.5
  [✔] pumpkin_pie-1.0.1
  [✔] recipe-book-delight-0.3.1-1.20
  [✔] rightclickharvest-fabric-4.3.0+1.20.6
  [✔] rotten-to-leather-3.0.0
  [✔] Searchables-fabric-1.20.6-1.0.1
  [✔] short-grass-1.3.0
  [✔] sixstairs-1.20.6-10-fabric
  [✔] skinlayers3d-fabric-1.6.7-mc1.20.6
  [✔] smoothscroll-2.1.2-1.20.5
  [✔] sodium-fabric-0.5.11+mc1.20.6
  [✔] sound-physics-remastered-fabric-1.20.6-1.4.5
  [✔] Sounds-1.1.4+1.20.6
  [✔] storagedelight-24.09.11-1.20-fabric
  [✔] supermartijn642configlib-1.1.8-fabric-mc1.20.6
  [✔] tcdcommons-3.12.3+fabric-1.20.6
  [✔] tia-1.20-1.1-fabric
  [✔] villagernames-1.20.6-8.1
  [✔] waig-1.1.5-mc1.20-and-newer
  [✔] YetAnotherConfigLib-3.5.0+1.20.6-fabric

### Logs

https://mclo.gs/4VpswBM

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by 22858** [comment]
you should use 1.21 instead of 1.20.6

**Comment by ChrysanthCow** [comment]
1.20.6 is kinda a dead water version for modding, especially due to 1.21.1 happening so soon after it.
A backport will not happen, so I'm closing this issue as not planned.
