### ISSUE TITLE
Knives incompatible with NoTreePunching

### ISSUE THREAD

**Issue by PlayerXYT** [MehVahdJukaar/FarmersDelightRefabricated#96]
### Minecraft version

1.20.1

### Farmer's Delight version

2.1.6

### Fabric Loader version

0.16.5

### Fabric API version

0.92.2+1.20.1

### Description

Knives have the same recipe as the ones provided by NoTreePunching. This makes one mod unusable, in this case NoTreePunching takes precedence and overrides the other recipe in the crafting table.

See [#312](https://github.com/alcatrazEscapee/no-tree-punching/issues/312)

### Steps to reproduce

Install NTP
Make knife
Try to cut meat on the cutting board

### Mod list

	- ad_astra 1.15.18
	   \-- javazoom_jlayer 1.0.1
	- animatica 0.6.1+1.20.4
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- betterf3 7.0.2
	- bitsandchisels 2.7.3
	   \-- stacc 1.5.2+boneless2ahhhh
	- botarium 2.3.4
	   \-- team_reborn_energy 3.0.0
	- capes 1.5.2+1.20
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- cccbridge 1.6.2b-fabric
	- charmofundying 6.5.0+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- chat_heads 0.12.13
	- cicada 0.8.3+1.20.1
	- citresewn 1.1.5+1.20.1
	   \-- citresewn-defaults 1.1.5+1.20.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- collective 7.84
	- computercraft 1.113.0
	   |-- cc_tweaked_cobalt 0.9.3
	   |-- com_electronwill_night-config_core 3.6.7
	   |-- com_electronwill_night-config_toml 3.6.7
	   |-- com_jcraft_jzlib 1.1.3
	   |-- io_netty_netty-codec-http 4.1.82
	   |-- io_netty_netty-codec-socks 4.1.82
	   \-- io_netty_netty-handler-proxy 4.1.82
	- connected-doors 1.2+1.20
	- continuity 3.0.0-beta.5+1.20.1
	- controlling 12.0.2
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_copper_and_zinc 1.4.0
	- create_interactive 1.0.3-beta.2+e045de2a48
	- create_train_perspective 0.6.1+mc1.20.1
	- createcontraptionterminals 1.0.0
	- diamond_nuggets 1.3
	- do_a_barrel_roll 3.6.1+1.20.1
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- dogslie 1.3.0
	- dynamic_fps 3.6.3
	   \-- net_lostluma_battery 1.1.0
	- elitex 1.2
	- elytraslot 6.4.2+1.20.1
	   \-- mixinsquared 0.1.2-beta.6
	- emotecraft 2.2.7-b.build.50
	   |-- bendy-lib 4.0.0
	   \-- player-animator 1.0.2-rc1+1.20
	- entity_model_features 2.2.3
	- entity_texture_features 6.2.2
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.7
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- fabricskyboxes 0.7.3+mc1.20.1
	- fallingleaves 1.15.6
	- farmersdelight 1.20.1-2.1.6+refabricated
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_config 2.3.4+1.20.1
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   \-- porting_lib_tool_actions 2.3.4+1.20.1
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- freecam 1.2.1+1.20
	- geckolib 4.4.9
	   \-- com_eliotlash_mclib_mclib 20
	- hideexperimentalwarning 1.2
	- ichunutil 1.0.0
	- immediatelyfast 1.2.20+1.20.4
	   \-- net_lenni0451_reflect 1.3.4
	- immersive_aircraft 1.0.1+1.20.1
	   \-- org_mariuszgromada_math_mathparser_org-mxparser 5.2.1
	- immersive_melodies 0.3.0+1.20.1
	- immersivemc 1.5.0-beta1
	- indium 1.0.34+mc1.20.1
	- interiors 0.5.3+fabric-mc1.20.1
	- item_obliterator 2.3.0
	- java 17
	- jei 15.14.0.64
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazydfu 0.1.3
	- led 1.6.0
	   |-- interference 1.7.0
	   \-- jmxl 1.4+mc1.20.2
	- linsapi 1.4.6
	   \-- blue_endless_jankson 1.2.2
	- lithium 0.11.2
	- luphieclutteredmod 2.1.0+1.20.1
	- man_of_many_planes 0.1.0+1.20.1
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- moderntrainparts 0.1.7-fabric-mc1.20.1-cr0.5.1-f
	   \-- mm 2.3
	- modmenu 7.2.2
	- moreculling 1.20.4-0.24.0
	   \-- conditional-mixin 0.3.2
	- mousetweaks 2.26
	- mr_create_manofmanyplanes 1.0
	- naiy 1.3.3
	- necronomicon 1.4.2
	- no-telemetry 1.8.0
	- nochatreports 1.20.1-v2.2.2
	- northerncompass 1.20.1-1.1.0
	- notenoughanimations 1.7.5
	- notreepunching 7.1.0
	- oldmclogo 1.1.0
	- oth3r-sit 1.1.10+1.20.1
	- owo 0.11.2+1.20
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.8.3+1.14.4-1.21
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- potioncauldron 1.0.1+mc1.20
	- progressive-raids 1.0.0
	- railroadblocksaddon 0.4.0
	- railways 1.6.4+fabric-mc1.20.1
	   \-- mm 2.3
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.29
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- roadworks 1.0.0-beta1
	- rrls 4.0.6.1+mc1.20.1-fabric
	- saros_road_signs_mod 2.0
	- searchables 1.0.3
	- shulkerboxtooltip 4.0.4+1.20.1
	- sizeshiftingpotions 1.7.1
	   \-- midnightlib 1.4.1
	- skinlayers3d 1.6.7
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- straightenup 1.2.0
	- tacz 1.0.2-hotfix2
	   |-- com_github_286799714_luaj_luaj-core 3.0.3
	   |-- com_github_286799714_luaj_luaj-jse 3.0.3
	   |-- mkb 1.2.0
	   |-- org_apache_commons_commons-math3 3.6.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_entity 2.3.4+1.20.1
	        \-- porting_lib_mixin_extensions 2.3.4+1.20.1
	- tconstruct 1.20.1-3.6.4.279
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- mantle 1.20.1-1.9.269
	   |    |-- com_google_code_findbugs_jsr305 3.0.2
	   |    \-- star 1.5.2+1.20.1
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |-- porting_lib_attributes 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.4+1.20.1
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |-- porting_lib_common 2.3.4+1.20.1
	   |-- porting_lib_config 2.3.4+1.20.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_data 2.3.4+1.20.1
	   |-- porting_lib_entity 2.3.4+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_fluids 2.3.4+1.20.1
	   |-- porting_lib_items 2.3.4+1.20.1
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |-- porting_lib_model_loader 2.3.4+1.20.1
	   |-- porting_lib_models 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |-- porting_lib_tool_actions 2.3.4+1.20.1
	   |-- porting_lib_transfer 2.3.4+1.20.1
	   \-- porting_lib_utility 2.3.4+1.20.1
	- toms_storage 1.6.8
	- trainperspectivefix 1.0.0
	- trainutilities 2.2.0
	- trepscars 0.9-1.20.1
	- trinkets 3.7.2
	- uteamcore 5.1.4.312
	- valkyrienskies 2.3.0-beta.5
	- vs_clockwork 1.20.1-0.1.16-fabric-b3b22e39fe
	- vs_eureka 1.5.1-beta.3
	- waveycapes 1.4.9
	- yet_another_config_lib_v3 3.5.0+1.20.1-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
https://github.com/alcatrazEscapee/no-tree-punching/issues/312#issuecomment-2391253284

This is moreso on the pack maker to solve as said by the other repo. I remember a mod that allows you to select what to craft from conflicting recipes, but i forgot the name.

Changing the recipe on either mod would cause more issues than it would solve.
