### ISSUE TITLE
Sweeping Edge can be applied to both Knives and Skillets despite not working at all

### ISSUE THREAD

**Issue by MiziraGamez** [MehVahdJukaar/FarmersDelightRefabricated#98]
### Minecraft version

1.21.1

### Farmer's Delight version

2.1.9

### Fabric Loader version

0.16.2

### Fabric API version

0.104.0

### Description

In 1.21 versions of the mod, all knives and the skillet item can receive the Sweeping Edge enchantment, despite the enchantment having no effect on anything except for a sword.

This is likely occurring due to tagging the items within the minecraft:enchantable/sword tag, which in vanilla is used for Looting and for Sweeping Edge. This would imply that the issue also occurs on the Forge/NeoForge versions as well.
Attempting this bug on versions prior to 1.21 (I personally tested with 1.20.1 of Refab) results in the items being flagged as incompatible with Sweeping Edge, further proving the tags being the issue.

The easiest solution would be to simply remove the items from the sword tag, but this method would also remove Looting from being able to be applicable to them. Unfortunately, one would have to edit the compatibility of Looting directly (via editing the enchantment json) into a new tag in order for it to be allowed on Swords, Skillets, and Knives, which could cause some trouble for other mods/datapacks' compatibility down the line.

### Steps to reproduce

1. Load into a world with Farmers Delight Refabricated. (due to likely source of bug I have reason to suspect it also affects the main Forge/NeoForge versions
2. Give yourself any knife and a skillet
3. Use the command /enchant (target selector: self) minecraft:sweeping_edge 3 when holding the knife and when holding the skillet
4. Both items should now receive the enchantment.
5. Spawn a group of mobs to attack with the enchanted items
6. Observe that the sweeping effect does not occur at all, as the enchantment only modifies the base effect from swords, not applying the sweeping attack itself to the item.

### Mod list

Farmers Delight Refabricated

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
This would be an issue for the NeoForge version of Farmer's Delight. I'd report to them.

https://github.com/vectorwing/FarmersDelight
